- portals/devportal/package.json
- portals/publisher/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
- portals/publisher/source/src/app/components/Apis/Details/GoTo/Components/GoToSuggestions.jsx
- portals/publisher/source/src/app/components/Apis/Details/GoTo/RouteMappings.jsx
- portals/publisher/source/src/app/data/Constants.js
In this PR:
- Fix for https://github.com/wso2/product-apim/issues/11317
- Change conflicting devportal webpack devserver port
- Update goto search terms (add comments etc)
> Fix endpoint security popup issue

- portals/admin/jaggery.conf
- portals/admin/services/login/idp.jag
- portals/admin/services/login/login_callback.jag
- portals/admin/services/logout/logout.jag
- portals/admin/services/settings/settings.jag
- portals/admin/services/utils.js
- portals/admin/site/public/conf/settings.js
- portals/admin/site/public/pages/index.jag.hbs
- portals/admin/source/src/app/ProtectedApp.jsx
- portals/admin/source/src/app/data/APIClient.js
- portals/admin/source/src/app/data/Utils.js
- portals/devportal/services/login/idp.jag
- portals/devportal/services/login/login_callback.jag
- portals/devportal/services/logout/logout.jag
- portals/devportal/services/utils.js
- portals/devportal/site/public/theme/settings.js
- portals/devportal/source/src/app/data/APIClient.jsx
- portals/devportal/source/src/app/data/Utils.jsx
- portals/publisher/services/login/idp.jag
- portals/publisher/services/login/login_callback.jag
- portals/publisher/services/logout/logout.jag
- portals/publisher/services/utils.js
- portals/publisher/site/public/conf/settings.js
- portals/publisher/source/src/app/data/APIClient.js
- portals/publisher/source/src/app/data/Utils.js
proxy_context_path does not work as expected
Fixing issue https://github.com/wso2/product-apim/issues/11263
> Fixing issue https://github.com/wso2/product-apim/issues/11263

- portals/publisher/site/public/conf/settings.js
- portals/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/source/src/app/data/api.js
Public fix for https://github.com/wso2/product-apim/issues/11291
https://github.com/wso2-support/carbon-apimgt/pull/3336
https://github.com/wso2-support/carbon-apimgt/pull/3326
> Fixing Limited view of throttling tiers in Publisher portal issue

- portals/admin/package-lock.json
- portals/admin/package.json
- portals/devportal/package-lock.json
- portals/devportal/package.json
- portals/devportal/source/src/DevPortal.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- portals/publisher/package-lock.json
- portals/publisher/package.json
- portals/publisher/source/src/app/ProtectedApp.jsx
- portals/publisher/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- portals/publisher/source/src/app/data/SamplePizzaShack.js
Fixing UI part of wso2/product-apim#11308
Public fix for wso2/product-apim#11358
> Fixing key generation unlimited throttling policy disabled UI releated issues

- portals/publisher/site/public/conf/settings.js
- portals/publisher/source/src/app/data/api.js
Fixes #https://github.com/wso2/product-apim/issues/10760
> Fixes issue #10760

- portals/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
- portals/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx
- portals/devportal/source/src/app/components/Applications/Details/index.jsx
Fixes #https://github.com/wso2/product-apim/issues/11254
> Fixes issue #11254

- portals/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
Fixing https://github.com/wso2/product-apim/issues/11398
> Fixing add comment section not visible for different email address users

- portals/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
- portals/publisher/source/src/app/data/APIValidation.js
Fixes https://github.com/wso2/product-apim/issues/11310
> Fixes issue #11310

- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
fix https://github.com/wso2/product-apim/issues/11338
> Validate tag name length to 30

- portals/devportal/site/public/locales/en.json
- portals/devportal/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
- portals/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiConsole.jsx
- portals/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- portals/devportal/source/src/app/components/Apis/Details/Environments.jsx
- portals/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLConsole.jsx
- portals/devportal/source/src/app/components/Apis/Listing/APICards/APIThumbPlain.jsx
- portals/devportal/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/NewEndpointCreate.jsx
- portals/publisher/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
- portals/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/OperationsSelector.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx
Frontend changes for wso2/product-apim#11587
https://github.com/wso2/product-apim/issues/11737
> Frontend changes for security in Prototyped APIs feature

- portals/publisher/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
As $subject, this will resolve the version in server urls in publisher try out console.
- https://github.com/wso2/product-apim/issues/11614
> Fix version resolving in the api context in tryout console

- portals/admin/site/public/locales/en.json
- portals/admin/site/public/locales/fr.json
- portals/admin/source/src/app/components/RolePermissions/Commons/SelectPermissionsStep.jsx
- portals/admin/source/src/app/components/RolePermissions/ListRoles.jsx
This PR fixes the following issues,
1. Scope Assignment UI search for roles
2. Role search UI bug
Fixes: https://github.com/wso2/product-apim/issues/10507
Fixes: https://github.com/wso2/product-apim/issues/10538
> Add searching function to scope assignments

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
As $subject, this will add white space validation when adding the operations.
- https://github.com/wso2/product-apim/issues/11630
> Add white space validation for operatons

- portals/publisher/source/src/app/components/Apis/Details/Documents/View.jsx
> Disable download button in Doc detail page in case a doc is not yet attached

- portals/publisher/package-lock.json
- portals/publisher/package.json
- portals/publisher/site/public/locales/en.json
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/DefinitionOutdated.jsx
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/WSDL.jsx
- portals/publisher/source/src/app/components/ServiceCatalog/CreateApi.jsx
- portals/publisher/source/src/app/components/ServiceCatalog/Listing/Overview.jsx
- portals/publisher/source/src/app/components/ServiceCatalog/Listing/components/ServiceCard.jsx
- portals/publisher/source/src/app/data/Utils.js
$subject
Related Issue: https://github.com/wso2/product-apim/issues/11746
Related EPIC: https://github.com/wso2/micro-integrator/issues/2397
> Adding wsdl definition support for Service Catalog and publisher UIs

- portals/devportal/package-lock.json
- portals/devportal/package.json
As $subject, this will upgrade the swagger-ui and swagger react libraries to fix the multipart issue.
1. https://github.com/wso2/product-apim/issues/11693
> Upgrade swagger ui librbary to fix multipart issue

- portals/publisher/openapitools.json
- portals/publisher/package-lock.json
- portals/publisher/package.json
- portals/publisher/services/dev_proxy/auth_login.js
- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Configuration/Topics.jsx
- portals/publisher/webpack.config.js
fixing https://github.com/wso2/product-apim/issues/11487
> fixing https://github.com/wso2/product-apim/issues/11487

- portals/admin/package-lock.json
- portals/admin/package.json
- portals/admin/source/src/app/components/Throttling/Custom/AddEdit.jsx
- portals/devportal/package-lock.json
- portals/devportal/package.json
- portals/package-lock.json
- portals/package.json
- portals/publisher/package-lock.json
- portals/publisher/package.json
This PR is updating the swagger-client and sql-formatter to latest versions.
> This PR is updating the swagger-client and sql-formatter to latest versions.

- portals/publisher/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
Resolves issue 1 in https://github.com/wso2/product-apim/issues/12104
> Change default endpoint optimize type to leave-as-is

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Resolves https://github.com/wso2/product-apim/issues/11919
> Replace static key manager tabs with scrollable tabs

- tests/README.md
This PR adds README.md file to APIM 3.2.0 UI tests.
> Add README to APIM 3.2.0 UI tests

- portals/publisher/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEditWorkspace.jsx
Fixes https://github.com/wso2/product-apim/issues/11312
> Remove deprected and retired APIs from API product dropdown list

- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- Fixes https://github.com/wso2/product-apim/issues/12077
> Fix issues in creating and deploying revisions at once

- portals/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- https://github.com/wso2/product-apim/issues/12228
> Fix error messages when inputting duplicate context.

- portals/publisher/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
Fixes https://github.com/wso2/product-apim/issues/12183
> View EP certs for read-only user

- portals/publisher/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEditWorkspace.jsx
Fix: https://github.com/wso2/product-apim/issues/12110
> Fixing product resource selection issue

- portals/publisher/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
Fixes 
- https://github.com/wso2/product-apim/issues/12239
- https://github.com/wso2/product-apim/issues/12285
> Fix issues related to Solace API deployment

- portals/admin/source/src/app/data/api.js
Fixes https://github.com/wso2/product-apim/issues/12369
> Add missing provider parameter for REST call

- portals/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
Fixes https://github.com/wso2/product-apim/issues/12366
> Fixing key gen wizard not working issue

- portals/admin/services/constants.jag
- portals/admin/source/dev/auth_login.js
- portals/admin/source/src/app/data/Utils.js
- portals/devportal/source/dev/webpack/auth_login.js
- portals/publisher/openapitools.json
- portals/publisher/services/constants.jag
- portals/publisher/services/dev_proxy/auth_login.js
- portals/publisher/services/login/login_callback.jag
- portals/publisher/services/refresh/refresh.jag
- portals/publisher/source/Tests/Utils/restAPI.mock.tsx
- portals/publisher/source/src/app/data/Utils.js
- portals/publisher/source/src/app/webWorkers/swagger.worker.js
- portals/publisher/webpack.config.js
- tests/cypress/integration/admin/index.spec.js
- tests/cypress/integration/publisher/API/REST/Create/defaultAPI.delete.spec.js
- tests/cypress/integration/publisher/ServiceCatalog/services.create.spec.js
> Adding version upgrade changes in publisher and admin portals

- portals/publisher/openapitools.json
- portals/publisher/source/src/app/data/ServiceCatalogClient.js
> Missing service catelog changes

- portals/publisher/openapitools.json
> Fixing issue in openapitools.json file

- portals/devportal/source/src/DevPortal.jsx
- portals/publisher/pom.xml
- portals/publisher/source/src/Publisher.jsx
- portals/publisher/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/source/src/app/components/Apis/Details/NewOverview/Overview.test.tsx
- portals/publisher/source/src/app/data/AuthManager.js
Fixing
Publisher Portal Access Issues with the assigned user roles
https://github.com/wso2/product-apim/issues/12226
Devportal home page is getting flickered once
https://github.com/wso2/product-apim/issues/12233
This update removes the limitation to create API having context /foo with abcd/foo and abcd/efgh/foo.
https://github.com/wso2/product-apim/issues/12218
> Fixing multiple issues related to patches

- portals/publisher/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- Fixes https://github.com/wso2/product-apim/issues/12408
> Fix issues in passing environments as list to revision

- portals/publisher/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/source/src/app/data/Constants.js
e04fb0a3b8084390b30e90c3e260eaa7fe95fbc5 fixes https://github.com/wso2/product-apim/issues/12377
fc47e40221e9a915e671a9f7db79c9d84ddcb572 fixes https://github.com/wso2/product-apim/issues/12371
> Fixes issues in endpoint security

- portals/devportal/source/src/app/components/Apis/Listing/APICards/APIThumbPlain.jsx
- portals/devportal/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
-  Fixes https://github.com/wso2/product-apim/issues/12407
> Adding a chip for solace API

- portals/publisher/source/src/app/components/Apis/Details/Comments/CommentAdd.jsx
- portals/publisher/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
- portals/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
Fix https://github.com/wso2/product-apim/issues/12460
Fix https://github.com/wso2/product-apim/issues/12373
Fix https://github.com/wso2/product-apim/issues/12503
> Fix UI issues

- portals/devportal/source/src/app/components/Apis/Details/Comments/Comments.jsx
Fix https://github.com/wso2/product-apim/issues/12450
> Fix comment add issue

- portals/publisher/source/src/app/components/Apis/Details/Policies/GatewaySelector.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/OperationPolicy.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/OperationsGroup.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
> Disabled CC radio button for policies

- portals/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
Related issue: https://github.com/wso2/product-apim/issues/11204
> Fixing UI issue for empty array

- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
Fixes https://github.com/wso2/product-apim/issues/12370
> Fix continuous api calls issue of streaming apis deployments page

- portals/publisher/source/src/app/data/defaultTheme.js
To update the analytics link in publisher UI to `https://console.choreo.dev/insights`.
- Resolves https://github.com/wso2/product-apim/issues/12374
> Update analytics link in publisher UI

- portals/admin/source/src/app/components/Throttling/Advanced/ConditionalGroup.jsx
Fixes https://github.com/wso2/product-apim/issues/12474
> Fix conditional group text wrapping

- portals/devportal/package-lock.json
- portals/devportal/package.json
- portals/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
Fixes https://github.com/wso2/product-apim/issues/12496
> Enable stop button for GraphQL subscriptions

- portals/admin/package-lock.json
- portals/admin/package.json
- portals/admin/source/src/app/components/Base/index.jsx
- portals/admin/source/src/app/components/Shared/Alert.jsx
- portals/admin/source/src/app/components/Throttling/Custom/AddEdit.jsx
- portals/devportal/package-lock.json
- portals/devportal/package.json
- portals/devportal/source/src/app/components/Base/index.jsx
- portals/devportal/source/src/app/components/Shared/Alert.jsx
1. Added the same alert components from publisher to admin and devportal.
2. Fixing https://github.com/wso2/product-apim/issues/12472
> Fixing pre beta UI issues

- portals/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
Fixing https://github.com/wso2/product-apim/issues/12462
> Fixing product-apim/issues/12462

- portals/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- Fixes https://github.com/wso2/product-apim/issues/12638
> Enable publish button for solace APIs in Life cycle tab

- portals/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
Fixes https://github.com/wso2/product-apim/issues/12613
> [UI] Fix issue with graphql tryout page going blank

- portals/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/source/src/app/data/api.js
Fixing https://github.com/wso2/product-apim/issues/12454
> Fixing beta UI issues

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Fixes https://github.com/wso2/product-apim/issues/12492
> Fix UPDATE button is getting enabled when refreshing the page

- portals/devportal/source/src/app/components/Apis/Details/SourceDownload.jsx
Fix https://github.com/wso2/product-apim/issues/12649
> Fix download button

- portals/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
Fixes https://github.com/wso2/product-apim/issues/12629
> Fix api property edit, delete issue

- portals/publisher/source/src/app/components/Apis/Details/Policies/GatewaySelector.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/Policies.tsx
> Policy gateway type change handling.

- portals/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- portals/devportal/source/src/app/components/Apis/Details/Credentials/SubscriptionTableRow.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Fixes https://github.com/wso2/product-apim/issues/12602
> Fix keymanager not disabled issue after disabling through publisher

- portals/publisher/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
As $subject, this will fix the streaming API publishing issue in publisher create API view.
- https://github.com/wso2/product-apim/issues/12609
> Fix streaming APIs publishing issue in publisher create API view

- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/RuntimeConfigurationWebSocket.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/SaveOperationPolicies.tsx
- portals/publisher/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEdit.jsx
- portals/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/SaveOperations.jsx
- portals/publisher/source/src/app/components/Shared/CustomSplitButton.jsx
Fixes https://github.com/wso2/product-apim/issues/12523
> Fix api deploy allowed with no endpoints and plans

- portals/devportal/site/public/locales/en.json
- portals/devportal/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- portals/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx
UI fix for https://github.com/wso2/product-apim/issues/12458
Alert when the request is sent for approval 
Alert when trying to update an application which has a pending approval request.
> Add tier pending notification and edit message

- portals/devportal/site/public/locales/en.json
- portals/devportal/source/src/app/components/Applications/Listing/AppsTableContent.jsx
Fix for https://github.com/wso2/product-apim/issues/12456
> Fix workflow approval pending display message

- portals/devportal/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/devportal/source/src/app/components/Apis/Listing/APICategoryThumb.jsx
- portals/devportal/source/src/app/components/Apis/Listing/ApiTagCloud.jsx
- portals/devportal/source/src/app/components/Apis/Listing/CategoryListingCategories.jsx
- portals/devportal/source/src/app/components/Apis/Listing/CommonListing.jsx
- portals/devportal/source/src/app/components/Apis/Listing/TagCloudListingTags.jsx
- portals/devportal/source/src/app/components/Applications/Details/Overview.jsx
- portals/devportal/source/src/app/components/Base/Header/GlobalNavbar.jsx
- portals/devportal/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
- portals/devportal/source/src/app/components/Base/Header/Search/SearchUtils.jsx
- portals/devportal/source/src/app/components/Base/index.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenExchangeKeyConfiguration.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManagerSummary.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- portals/devportal/source/src/app/components/Shared/LeftMenuItem.jsx
- portals/devportal/source/src/app/data/defaultTheme.js
Fixing wso2/product-apim#12590
Fixing wso2/product-apim#12589
Fixing wso2/product-apim#12679
> Fixing KM UI issues

- portals/publisher/source/src/app/components/Apis/Details/Policies/GatewaySelector.tsx
- Resolves https://github.com/wso2/product-apim/issues/12706
> Fix font size in gateway switch related dialog

- portals/admin/jaggery.conf
- portals/admin/site/public/locales/en.json
- portals/admin/site/public/pages/error-pages/401.html
- portals/admin/site/public/pages/error-pages/403.html
- portals/admin/site/public/pages/error-pages/404.html
- portals/admin/site/public/pages/error-pages/500.html
- portals/admin/site/public/pages/error-pages/error-page.html
- portals/admin/source/src/app/components/Throttling/Advanced/Delete.jsx
- portals/admin/source/src/app/components/Throttling/Custom/AddEdit.jsx
- portals/devportal/jaggery.conf
- portals/devportal/site/public/pages/error-pages/401.html
- portals/devportal/site/public/pages/error-pages/403.html
- portals/devportal/site/public/pages/error-pages/404.html
- portals/devportal/site/public/pages/error-pages/500.html
- portals/devportal/site/public/pages/error-pages/error-page.html
- portals/publisher/jaggery.conf
- portals/publisher/site/public/pages/error-pages/401.html
- portals/publisher/site/public/pages/error-pages/403.html
- portals/publisher/site/public/pages/error-pages/404.html
- portals/publisher/site/public/pages/error-pages/500.html
- portals/publisher/site/public/pages/error-pages/error-page.html
- Fixing error page when deleting advanced policies having resource ass… 
- Adding fixies for wso2/product-apim#12159
- Blocking source files public visibility
> Fixing Beta UI issues and porting patch fixes

- portals/publisher/source/src/app/components/Apis/Details/Policies/Policies.tsx
Fixes: https://github.com/wso2/product-apim/issues/12710
> policy related fixes in API policy view page

- portals/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/operationComponents/ListParameters.jsx
Fixing publish button disabled issue and resouce page broken issueFixing publish button disabled issue and resouce page broken issue
> Fixing publish button disabled issue

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
> updating deprecated message for - create api importing WSDL

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenExchangeKeyConfiguration.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- portals/devportal/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx
Fixing https://github.com/wso2/product-apim/issues/12759
> Fixing token exchange UI error

- portals/admin/site/public/locales/en.json
- portals/admin/site/public/locales/fr.json
- portals/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Fixing https://github.com/wso2/product-apim/issues/12791
> Adding Issuer to Resident KM config

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
Fixing https://github.com/wso2/product-apim/issues/12793
> changing prototype label to pre-release for mock apis

- tests/cypress/integration/admin/00-add-edit-delete-microgateway-environments.spec.js
- tests/cypress/integration/admin/02-add-edit-delete-application-throttle-policies.spec.js
- tests/cypress/integration/admin/03-add-edit-delete-subscription-throttle-policies.spec.js
- tests/cypress/integration/admin/05-add-custom-throttle-policies.spec.js
This PR fixes admin portal UI test failures.
> Fix admin portal UI test failures

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
- tests/cypress/integration/devportal/001-applications/05-test-application-sharing.specs.js
Test Case : Test Application Sharing
> Test Application Sahring

- portals/publisher/source/src/app/components/Apis/Details/Policies/AttachedPolicyForm/General.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/GeneralDetails.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyAttributes.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyViewForm.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/SourceDetails.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/UploadPolicyDropzone.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyList.tsx
- portals/publisher/source/src/app/components/CommonPolicies/Listing.jsx
- portals/publisher/source/src/app/components/Shared/CustomSplitButton.jsx
- tests/cypress/fixtures/api_artifacts/sampleAddHeader.j2
- tests/cypress/integration/publisher/017-api-policies/00-common-policy.specs.js
- tests/cypress/integration/publisher/017-api-policies/01-api-specific-policy.specs.js
This Pr contains two test cases as,
01. Common Policies
02. API Specific Policies
> Test cases: Operational Policy feature

- portals/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Fixes https://github.com/wso2/api-manager/issues/27
> Hide Connector Configurations for Resident KM

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
- portals/publisher/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
- portals/publisher/source/src/app/components/Shared/InlineMessage.jsx
- portals/publisher/source/src/app/data/api.js
Fixing https://github.com/wso2/product-apim/issues/12847 https://github.com/wso2/product-apim/issues/12848
> Subscription listing pagination fix and api definition update validation fix

- portals/admin/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Fixes https://github.com/wso2/api-manager/issues/101
> Fix issue in update scope in km configs

- portals/publisher/package-lock.json
- portals/publisher/package.json
- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/Linting/APILinting.tsx
- portals/publisher/webpack.config.js
In this PR:
- Add Spectral core and Ruleset packages
- Reference Spectral integration in `APILinting` component
TODO:
- Need to write Unit and Integration test using React testing library and E2E test using cypress
- Need to test `Error`, `Warning`, `Info` & `Hint` cases
- Need to implement Linter vs Swagger-UI toggle view in API definition editor
- Need to add linting support to `AsyncAPI specs`
> add stoplight spectral base

- portals/admin/source/src/app/components/AdvancedSettings/TenantConfSave.jsx
- tests/cypress/fixtures/api_artifacts/advanceConfigFlase.json
- tests/cypress/fixtures/api_artifacts/advanceConfigTrue.json
- tests/cypress/integration/admin/10-advanced-configurations.specs.js
- tests/cypress/integration/publisher/013-api-product/04-lifecycle-support-for-api-products.specs.js
This PR consist of two test cases as follows,
01.Advanced configurations - Admin Portal
02.Life cycle support for API Products
> Advance configuration in admin portal and life cycle support for API Products

- portals/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- portals/devportal/source/src/app/components/Apis/Details/Credentials/OriginalDevportalDetails.jsx
- portals/devportal/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/UpdateWithoutDetails.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
- portals/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
- tests/cypress/support/commands.js
Fixed the issue : [Original Dev Portal link was not working](https://github.com/wso2/api-manager/issues/150)
> Fixed original dev portal link in Developer Portal

- portals/devportal/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- portals/devportal/source/src/app/components/Apis/Details/Credentials/OriginalDevportalDetails.jsx
- portals/devportal/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/components/UpdateWithoutDetails.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
- portals/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
- tests/cypress/support/commands.js
UI integration test for the following feature: [Advertise only API (Third party API). ](https://github.com/wso2/product-apim/issues/10333)
This test contains,
1. Creating a third party api and publishing it
2. Checking if AsyncAPI has other protocols option enabled
3. Checking if all the necessary changes of the third party api feature is enabled
4. Checking if necessary prompts and labels are visible
5. Checking if the authorization header and value can be customized
> UI integration test case: Advertise only API feature

- portals/publisher/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
This PR fixes https://github.com/wso2/api-manager/issues/215
> Add an API state workflow reject message

- portals/admin/site/public/conf/userTheme.js
- portals/admin/source/src/app/ProtectedApp.jsx
- portals/admin/source/src/app/components/AdminPages/Addons/ListBase.jsx
- portals/admin/source/src/app/components/AdminPages/Dashboard/APICategoriesCard.jsx
- portals/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
- portals/admin/source/src/app/components/ApplicationSettings/ListApplications.jsx
- portals/admin/source/src/app/components/Base/Navigator.jsx
- portals/admin/source/src/app/components/Base/index.jsx
- portals/admin/source/src/app/components/KeyManagers/DeleteKeyManager.jsx
- portals/admin/source/src/app/components/KeyManagers/ListKeyManagers.jsx
- portals/admin/source/src/app/components/ManageAlerts/ManageAlerts.jsx
- portals/admin/source/src/app/components/RolePermissions/AdminTable/AdminTable.jsx
- portals/admin/source/src/app/components/RolePermissions/AdminTable/AdminTableBody.jsx
- portals/admin/source/src/app/components/RolePermissions/Commons/ListAddOns.jsx
- portals/admin/source/src/app/components/Throttling/Advanced/Delete.jsx
- portals/admin/source/src/app/components/Throttling/Advanced/List.jsx
- portals/admin/source/src/app/components/Throttling/Application/Delete.jsx
- portals/admin/source/src/app/components/Throttling/Application/List.jsx
- portals/admin/source/src/app/components/Throttling/Custom/Delete.jsx
- portals/admin/source/src/app/components/Throttling/Custom/List.jsx
- portals/admin/source/src/app/components/Throttling/Subscription/Delete.jsx
- portals/admin/source/src/app/components/Throttling/Subscription/List.jsx
Fixed the 508 compliance issues reported by the customer to the admin portal.
> Fix 508 Compliance Issues on Admin Portal

- portals/admin/source/src/app/components/AdminPages/Dashboard/TasksWorkflowCard.jsx
- portals/admin/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/source/src/app/components/Workflow/ApplicationDeletion.jsx
- portals/admin/source/src/app/components/Workflow/SubscriptionDeletion.jsx
- portals/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
- portals/devportal/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- portals/devportal/source/src/app/components/Applications/Details/Subscriptions.jsx
- portals/devportal/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- portals/devportal/source/src/app/components/Applications/Listing/Listing.jsx
- portals/devportal/source/src/app/data/Application.jsx
Application deletion and subscription deletion approval workflows introduced with this. Required UI changes and done here
> Application deletion, subscription deletion workflow implementation

- portals/admin/site/public/locales/en.json
- portals/admin/source/src/app/components/Base/index.jsx
- portals/devportal/site/public/locales/en.json
- portals/devportal/source/src/app/components/Base/index.jsx
- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Base/Footer/Footer.jsx
> Change WSO2 name

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/AWSLambda/Credentials.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/source/src/app/components/Apis/Details/Endpoints/endpointUtils.js
This PR adds UI changes to add configs related to sts assume role support. Fixes https://github.com/wso2/api-manager/issues/365.
> Add sts assume role support

- portals/devportal/source/src/app/components/Applications/Details/InfoBar.jsx
- portals/devportal/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- portals/publisher/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
Fix https://github.com/wso2/api-manager/issues/464, https://github.com/wso2/api-manager/issues/535
> Fix thumbnail updating issue in API info

- portals/admin/source/src/app/components/APICategories/AddEditAPICategory.jsx
Related to : https://github.com/wso2/product-apim/issues/12728
> Add UI validation for API Category Description

- .github/workflows/ui-test.yml
- tests/cypress/fixtures/api_artifacts/advanceConfigFlase.json
- tests/cypress/fixtures/api_artifacts/advanceConfigTrue.json
- tests/cypress/integration/devportal/001-applications/05-test-application-sharing.spec.js
- tests/cypress/integration/devportal/003-test/00-tryout-api-invocations-from-swagger-console.spec.js
- tests/cypress/integration/devportal/004-api-product/00-api-product-invoke-with-keys.spec.js
- tests/cypress/integration/e2e/developerFundamentalScenarios/01-create-api-from-scratch-and-publish.spec.js
- tests/cypress/integration/publisher/000-general/03-create-and-publish-graphql-api-with-all-information.spec.js
- tests/cypress/integration/publisher/001-api-create/06-solace-broker-integration.spec.js
- tests/cypress/integration/publisher/003-run-time-configs/05-oauth2-and-api-key-security.spec.js
- tests/cypress/integration/publisher/004-endpoints/05-add-security.spec.js
- tests/cypress/integration/publisher/004-endpoints/06-Import-delete-certificates.spec.js
- tests/cypress/integration/publisher/013-api-product/04-lifecycle-support-for-api-products.spec.js
- tests/cypress/integration/publisher/014-comments/00-add-comments-to-api.spec.js
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
- tests/cypress/integration/publisher/019-read-only-user/00-verify-that-read-only-user-cannot-create-update-api.spec.js
- tests/cypress/integration/publisher/020-prototyped-apis/00-try-out-resources-without-key-when-security-disabled.spec.js
- tests/cypress/integration/publisher/020-prototyped-apis/01-cannot-try-out-resources-without-key-when-security-enabled.spec.js
- tests/cypress/integration/publisher/020-prototyped-apis/02-can-try-out-resources-with-key-when-security-enabled.spec.js
- tests/cypress/support/commands.js
- tests/cypress/support/pages/adminPortal/ScopeAssignmentsPage.js
- tests/cypress/support/pages/devportal/DevPortalApisPage.js
- tests/cypress/support/utils.js
Fix intermittent test failures
> Fix test failures

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
Related to : https://github.com/wso2/product-apim/issues/12772
> Fix overview page API status UI misbehaviour

- portals/publisher/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/AttachedPolicyCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/DraggablePolicyCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfiguringDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/GeneralDetails.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyViewForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/Types.d.ts
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Types.d.ts
- portals/publisher/src/main/webapp/source/src/app/components/CommonPolicies/Listing.jsx
- tests/cypress/integration/publisher/017-api-policies/00-common-policy.spec.js
- tests/cypress/integration/publisher/017-api-policies/01-api-specific-policy.spec.js
https://github.com/wso2/api-manager/issues/550
> Adding operation policy version support feature

- tests/cypress/fixtures/api_artifacts/lifecycle.json
- tests/cypress/fixtures/api_artifacts/tenant-conf.json
- tests/cypress/integration/publisher/011-lifecycle/03-add-custom-lifecycle-state.spec.js
- tests/cypress/support/commands.js
This is the UI test for the feature #https://github.com/wso2/api-manager/issues/314
> UI Tests - Adding a custom state to the lifecycle

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
**Purpose** 
- Fix context validation for tenants by appending the tenant domain to the context.
- Remove redundant context validation for context + version and validation applied only on context where the new version creation could be done through the separate UI available for creating new version.
> Fix context validation for tenants

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewCurl.jsx
fix https://github.com/wso2/api-manager/issues/44
> fix curl command

- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/navbar/GlobalNavLinks.jsx
- portals/publisher/src/main/webapp/source/src/app/data/AuthManager.js
Fix for https://github.com/wso2/product-apim/issues/12808
> Fix global scopes page to be visible only to Admin users

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/operationUtils.js
* https://github.com/wso2/api-manager/issues/528
> Introducing RegEx To OpenAPI Version Selection

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AdvertiseInfo.jsx
Fix wso2/api-manager/issues/148
> Add external endpoint validation

- portals/admin/client/public/Settings.js
- portals/admin/client/src/App.tsx
- portals/admin/client/src/constants/token.ts
- portals/admin/client/src/models/token-response.ts
- portals/admin/client/src/session.ts
- portals/admin/client/src/sign-in.ts
- portals/admin/package.json
This PR adds refresh token request & access token request implementations
> Add refresh token request

- tests/cypress/integration/01-publisher/004-endpoints/07-mock-api-and-test.spec.js
- tests/cypress/integration/02-devportal/004-test/00-tryout-api-invocations-from-swagger-console.spec.js
> Fix placeholder name issue

- portals/devportal/src/main/webapp/services/login/login_callback.jsp
Fixed redirection to dev portal if the user tries to access an anonymous API using a direct URL
Fix #https://github.com/wso2/api-manager/issues/23
> Fixed - can not directly access anonymous API with API URL

- portals/devportal/src/main/webapp/services/login/login_callback.jsp
- portals/publisher/src/main/webapp/openapitools.json
Fix https://github.com/wso2/product-apim/issues/12635
> Fix for unexpected redirection to the Home page of the devPortal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/OperationPolicy.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/OperationsGroup.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
Support policies at operation level for Choreo Connect similar to Synapse gateway.
https://github.com/wso2/product-apim/pull/12926
https://github.com/wso2/product-microgateway/pull/2983
https://github.com/wso2/product-microgateway/issues/2756
> [Choreo-Connect] Support policies at operation level

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/CommentOptions.jsx
- portals/publisher/src/main/webapp/source/src/app/data/User.js
Fix for https://github.com/wso2/product-apim/issues/12631
> Disabling the comment reply button for Internal/creator users

- tests/cypress/integration/publisher/021-api-linter-feature/00-lint-when-creating-api-with-swagger-url.spec.skip.js
- tests/cypress/integration/publisher/021-api-linter-feature/01-lint-when-creating-api-with-swagger-file.spec.skip.js
- tests/cypress/integration/publisher/021-api-linter-feature/02-lint-when-creating-api-with-swagger-v2-url.spec.skip.js
- tests/cypress/integration/publisher/021-api-linter-feature/03-lint-when-creating-api-with-swagger-v2-file.spec.skip.js
- tests/cypress/integration/publisher/021-api-linter-feature/04-lint-when-creating-api-with-errornous-swagger-file.spec.skip.js
- tests/cypress/support/commands.js
> Fix API linter test failures when creating API

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/AppConfiguration.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Here two additional properties are added to Forgerock Key Manager to allow users to add Custom default scopes and change the client type to 'Public' whenever needed.
> Enhancement in FR KM -additional Properties

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
Public fix for the issue https://github.com/wso2/api-manager/issues/704
> Checking http/https ports for configuring servers in tryout-console of Publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
This PR modifies the changes done by https://github.com/wso2/apim-apps/pull/374. This is the UI fix done for https://github.com/wso2/carbon-apimgt/pull/11639. This PR resolves https://github.com/wso2/api-manager/issues/942.
> Fix http endpoint display when not defined

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
Fix for https://github.com/wso2/api-manager/issues/902
> Fix for linter results filtering issue

- portals/admin/src/main/webapp/services/constants.jsp
- portals/admin/src/main/webapp/source/dev/auth_login.js
- portals/admin/src/main/webapp/source/src/app/data/Utils.js
- portals/devportal/src/main/webapp/services/constants.jsp
- portals/devportal/src/main/webapp/source/dev/webpack/auth_login.js
- portals/devportal/src/main/webapp/source/src/app/data/Utils.jsx
- portals/publisher/src/main/webapp/openapitools.json
- portals/publisher/src/main/webapp/services/constants.jsp
- portals/publisher/src/main/webapp/services/dev_proxy/auth_login.js
- portals/publisher/src/main/webapp/source/Tests/Utils/restAPI.mock.tsx
- portals/publisher/src/main/webapp/source/src/app/data/Utils.js
- portals/publisher/src/main/webapp/source/src/app/webWorkers/swagger.worker.js
- portals/publisher/src/main/webapp/webpack.config.js
- tests/cypress/integration/admin/10-advanced-configurations.spec.js
- tests/cypress/integration/devportal/001-applications/04-exchange-key-managers.spec.js
- tests/cypress/support/commands.js
- tests/cypress/support/utils.js
$subject
Resolves https://github.com/wso2/api-manager/issues/988
Related to https://github.com/wso2/api-manager/issues/958
> Upgrade REST API version for 4.2.0

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
Fix the front-end issue mentioned in https://github.com/wso2/api-manager/issues/951 step 9.
> Adding the filtering based on API policy versioning

- portals/publisher/src/main/webapp/openapitools.json
- portals/publisher/src/main/webapp/source/Tests/Utils/setupUtils.ts
> Revert "Fixing OAS definition download issue"

- portals/admin/src/main/webapp/services/constants.jsp
- portals/admin/src/main/webapp/source/dev/auth_login.js
- portals/admin/src/main/webapp/source/src/app/data/Utils.js
- portals/devportal/src/main/webapp/services/constants.jsp
- portals/devportal/src/main/webapp/source/dev/webpack/auth_login.js
- portals/devportal/src/main/webapp/source/src/app/data/Utils.jsx
- portals/publisher/src/main/webapp/openapitools.json
- portals/publisher/src/main/webapp/services/constants.jsp
- portals/publisher/src/main/webapp/services/dev_proxy/auth_login.js
- portals/publisher/src/main/webapp/source/Tests/Utils/restAPI.mock.tsx
- portals/publisher/src/main/webapp/source/src/app/data/Utils.js
- portals/publisher/src/main/webapp/source/src/app/webWorkers/swagger.worker.js
- portals/publisher/src/main/webapp/webpack.config.js
- tests/cypress/integration/admin/10-advanced-configurations.spec.js
- tests/cypress/integration/devportal/001-applications/04-exchange-key-managers.spec.js
- tests/cypress/support/commands.js
- tests/cypress/support/utils.js
> Revert "Upgrade REST API version for 4.2.0"

- tests/cypress/integration/devportal/000-general/03-self-signup.spec.js
- tests/cypress/integration/publisher/001-api-create/01-login-logout-from-publisher-as-super-tenant-user.spec.js
- tests/cypress/support/commands.js
$subject
Fix for https://github.com/wso2/api-manager/issues/1047
> Fix cypress test failure

- README.md
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- tests/cypress/fixtures/multipleDeployments.json
- tests/cypress/fixtures/multipleEnvironments.json
- tests/cypress/integration/publisher/015-deployments/02-verify-gateway-environments.spec.js
Test case for https://github.com/wso2/api-manager/issues/942.
> Add UI test to verify gateway environments

- tests/cypress/integration/devportal/000-general/03-self-signup.spec.js
$subject 
related to https://github.com/wso2/api-manager/issues/1047
> Fix self signup test failure

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLConsole.jsx
Purpose: Change the icon type from warning to info
> Change icon type

- tests/cypress/integration/publisher/004-endpoints/09-add-security-spec-then-update-endpoints.js
> Test PR for https://github.com/wso2/apim-apps/pull/402
> Add add-security-spec-then-update-endpoints test case

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.test.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
Fixes https://github.com/wso2/api-manager/issues/1113
> Fix create API with yaml definition

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/GenerateDocument.jsx
- fixes https://github.com/wso2/api-manager/issues/1050
> Change stoplight UI laylout to sidebar

- portals/devportal/src/main/webapp/services/login/login_callback.jsp
Fix for https://github.com/wso2/api-manager/issues/1102
> Remove system out logs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/LinterUI/LinterUI.jsx
- tests/cypress/integration/admin/00-add-edit-delete-microgateway-environments.spec.js
- tests/cypress/integration/admin/01-add-edit-delete-advance-throttle-policies.spec.js
- tests/cypress/integration/admin/02-add-edit-delete-application-throttle-policies.spec.js
- tests/cypress/integration/admin/03-add-edit-delete-subscription-throttle-policies.spec.js
- tests/cypress/integration/admin/04-add-edit-delete-api-categories.spec.js
- tests/cypress/integration/admin/09-add-km.spec.js
- tests/cypress/support/commands.js
This PR fixes the comments in the following PRs.
- https://github.com/wso2/apim-apps/pull/267
- https://github.com/wso2/apim-apps/pull/283
> Fix formatting issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/SwaggerUI.jsx
Fixing wild card url issue in : https://github.com/wso2/api-manager/issues/1055
Patch : https://github.com/wso2-enterprise/wso2-apim-internal/issues/1206
(API count issue is not fixed as the behaviour is expected with registry indexing delays.)
(OpenAPI file upload show errors issue is already fixed in the public branch)
> Add fix to publisher wildcard pattern check to include version

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
related to: https://github.com/wso2/api-manager/issues/1210
Screenshots of updated UIs
> User should not be able to deploy retired apis

- portals/devportal/src/main/webapp/services/login/idp.jsp
- portals/devportal/src/main/webapp/services/login/login_callback.jsp
Fixes https://github.com/wso2/api-manager/issues/1194
related PR : https://github.com/wso2/carbon-apimgt/pull/11774
> Add pkce support for devportal

- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
- tests/cypress/support/commands.js
To address line exceeds 120 chars [comment](https://github.com/wso2/apim-apps/pull/276#discussion_r1054564751)
> Fixed line exceeds 120 chars

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Fixing https://github.com/wso2/api-manager/issues/19
> Fixed blank screen when "Resident Key Manager" is disabled

- pom.xml
Upgrades carbon-apimgt version
Related git issue : https://github.com/wso2/api-manager/issues/1267
> Upgrade carbon-apimgt version

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/DocList.jsx
Fixes below error during build.
```
[INFO] ERROR in 
[INFO] /home/jenkins/workspace/platform-builds/apim-apps/portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/DocList.jsx
[INFO]   230:1  error  Too many blank lines at the end of file. Max of 0 allowed  no-multiple-empty-lines
[INFO] 
[INFO] ✖ 2 problems (1 error, 1 warning)
[INFO]   1 error and 0 warnings potentially fixable with the `--fix` option.
[INFO] 
[INFO] [ERROR] Command execution failed.
[INFO] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[INFO]     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
[INFO]     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
[INFO]     at …
```
> Fix apim-apps build issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/DocList.jsx
Removed newline in DocList.jsx
Related to prod [apim-apps#425](https://github.com/wso2/apim-apps/pull/425/)
> Removed newline in DocList.jsx

- portals/devportal/src/main/webapp/site/public/locales/en.json
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/DocList.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/SourceDownload.jsx
Fixing UI changes for the fix https://github.com/wso2/api-manager/issues/558
> Fixing UI - Not able to get a Link to the Swagger Definition of an API in DevPortal

- tests/cypress/integration/publisher/021-api-linter-feature/10-lint-when-importing-api-with-errornous-swagger-file.spec.js
- tests/cypress/support/commands.js
fix failures of self-signup tests
> Fixes for UI Test failures 

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AWSLambda/Credentials.jsx
> Fix for - Issues with Lambda API when saving the Lambda API endpoint configs

- tests/cypress/integration/publisher/000-general/03-create-and-publish-graphql-api-with-all-information.spec.js
- tests/cypress/integration/publisher/019-read-only-user/00-verify-that-read-only-user-cannot-create-update-api.spec.js
- tests/cypress/support/commands.js
Relates to PR https://github.com/wso2/apim-apps/pull/281
> Fix formatting issues in UI tests

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/Certificates.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
Fixes: https://github.com/wso2/api-manager/issues/1397
> Update certificate aliasList

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/GenerateDocument.jsx
This PR consists of changes to change the generated documentation view in Devportal to sidebar from stacked.
This PR solves [api-manager#1451](https://github.com/wso2/api-manager/issues/1451)
> Changes documentation view in devportal to sidebar from stacked

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
Resolves: https://github.com/wso2/api-manager/issues/1101
> Change the linter message for API definition 

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx
Fixes https://github.com/wso2/api-manager/issues/1430
> Fix a bug in autofilling authorization header

- portals/publisher/src/main/webapp/source/src/app/ProtectedApp.jsx
- portals/publisher/src/main/webapp/source/src/app/data/AuthManager.js
$Subject
* https://github.com/wso2/api-manager/issues/524
> Adding public fixes to session timeout error message issue in publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/asyncapi/Runtime.jsx
Remove ending slashing and beginning slash and combine with a single slash
Fix https://github.com/wso2/api-manager/issues/1277
> Remove additional slash in websocket url mapping

- portals/admin/src/main/webapp/site/public/locales/en.json
- portals/admin/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/devportal/src/main/webapp/site/public/locales/en.json
- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Base/Footer/Footer.jsx
This commit changes footers for 2023 as APIM 4.2 will be released in that year.
This fixes https://github.com/wso2/api-manager/issues/1376
> Update publisher, devportal and admin footer

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateKeysStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GoToTryOut.jsx
Issue: https://github.com/wso2/api-manager/issues/1371
> Removed token exchange grant type from keygen wizard defaults

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
Fixing https://github.com/wso2/api-manager/issues/1576
> Fixing API visibility restriction base on roles not cleared properly issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
- tests/cypress/integration/publisher/004-endpoints/10-change-advanced-configuration.spec.js
The validation will only allow the user to add values 0-9 zero or more times
Public UI fix and tests for issue https://github.com/wso2/api-manager/issues/1591
> Validate endpoint advanced configuration numeric fields

- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/ListRoles.jsx
- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/TreeView/PermissionsSelector.jsx
- tests/cypress/integration/publisher/003-run-time-configs/05-oauth2-and-api-key-security.spec.js
Public Issue: https://github.com/wso2/api-manager/issues/556
> Resolving the test case failure due to faster execution.

- portals/devportal/src/main/webapp/package-lock.json
- portals/devportal/src/main/webapp/package.json
Remove Swagger-ui since it's not used
> Remove Swagger-ui since it's not used

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Monetization/index.jsx
Public fix for issue https://github.com/wso2/api-manager/issues/1682
> Remove unnecessary setState

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Prototype/MockScriptOperation.jsx
Fixes https://github.com/wso2/api-manager/issues/1638
> Add changes to fix Prototype Impl page

- portals/devportal/src/main/webapp/services/login/login_callback.jsp
- portals/publisher/src/main/webapp/services/login/idp.jsp
- portals/publisher/src/main/webapp/services/login/login_callback.jsp
Related to https://github.com/wso2/api-manager/issues/1875
> Bypass Client Secret using PKCE

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/LastUpdatedTime.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
Read `lastUpdatedTimestamp` value to display Last Updated Time
Fix https://github.com/wso2/api-manager/issues/1860
> Read lastUpdatedTimestamp value to display Last Updated Time

- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Usage/Usage.jsx
This PR fixes https://github.com/wso2/api-manager/issues/1938
> [Public] - Fix scope usage issue fix

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/KeyValidation.jsx
Fix https://github.com/wso2/api-manager/issues/1951
> Fixed the issue in updating Key Manager after Advanced Configuration changes

- portals/admin/src/main/webapp/site/public/conf/settings.json
- portals/admin/src/main/webapp/source/src/app/data/api.js
Public Issue: https://github.com/wso2/api-manager/issues/1947
> Adding configuration for displayed workflow limit

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/CreateApi.jsx
This PR modifies UI context validation logic to check for malformed contexts.
> Modify context validation logic

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
https://github.com/wso2/api-manager/issues/97
This PR adds filter functionality for subscription list based on subscriber name in publisher
> Adds search functionality based on subscriber for subscriptions

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
Purpose
Warning message will now appear in create API page and only when Generate REST APIs is selected.
Fixes issue: https://github.com/wso2/api-manager/issues/1545 and https://github.com/wso2/api-manager/issues/73
> Warning message improvement

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- tests/cypress/integration/publisher/000-general/03-create-and-publish-graphql-api-with-all-information.spec.js
- tests/cypress/integration/publisher/019-read-only-user/00-verify-that-read-only-user-cannot-create-update-api.spec.js
This PR fixes some Cypress test failures.
> Fix cypress test failures

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AdvertiseInfo.jsx
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
fixes: https://github.com/wso2/api-manager/issues/2071
> Fix: Save Button disabled issue in Basic Info

- tests/cypress/integration/publisher/003-run-time-configs/06-add-api-key-header.spec.js
Resolves https://github.com/wso2/api-manager/issues/1672
UI tests for https://github.com/wso2/apim-apps/pull/462
> UI test for custom api key header feature

- tests/cypress/integration/admin/11-change-the-owner-of-application.spec.js
- tests/cypress/integration/devportal/000-general/05-download-sdk.spec.js
Following test cases are added to developer and admin sections
admin/11-change-the-owner-of-application.spec.js
devportal/000-general/05-download-sdk.spec.js
> Adding test cases to developer and admin portals

- portals/publisher/src/main/webapp/source/src/app/data/APIProduct.js
This PR fixes https://github.com/wso2/api-manager/issues/2176
> Change request params

- portals/publisher/src/main/webapp/source/src/app/components/Shared/redirecting.css
Introduced this PR to fix https://github.com/wso2/api-manager/issues/2277
> Remove height property from parent component

- portals/publisher/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
This PR fixes https://github.com/wso2/api-manager/issues/2250
> Add maximum scope count as a parameter configurable from settings.js

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewVersion/NewVersion.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/CreateNewVersionButton.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
- portals/publisher/src/main/webapp/source/src/app/data/ScopeValidation.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
- tests/cypress/integration/devportal/004-api-product/00-api-product-invoke-with-keys.spec..skipjs
- tests/cypress/integration/publisher/013-api-product/02-create-a-new-revision-for-the-api-product-and-deploy.spec.js
- tests/cypress/integration/publisher/013-api-product/03-undeploy-new-revision-of-api-product.spec.js
- tests/cypress/integration/publisher/013-api-product/04-lifecycle-support-for-api-products.spec.js
- tests/cypress/integration/publisher/013-api-product/05-create-new-version-of-api-product.spec.js
Related Issue: https://github.com/wso2/api-manager/issues/2164
> [Feature] UI fixes for versioning support of API Products

- tests/cypress/integration/devportal/000-general/03-self-signup.spec.js
Code reformatting for https://github.com/wso2/apim-apps/pull/375
> Code reformatting of self-signup.spec test case

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/ApiTagThumb.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/TagCloudListingTags.jsx
> Fix UI issues in API grouping

- portals/devportal/src/main/java/org/wso2/carbon/apimgt/ui/devportal/Util.java
- portals/publisher/src/main/java/org/wso2/carbon/apimgt/ui/publisher/Util.java
> Fix for https://github.com/wso2-support/apim-apps/pull/195

- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/Overview.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/index.jsx
This PR fixes UI-based unlimited tier disabling issue in applications.
Resolves: https://github.com/wso2/api-manager/issues/2426
> Fix UI based unlimited tier disabling issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Fix for issue: https://github.com/wso2/api-manager/issues/2472
> Fix for refresh issue in revisions

- portals/devportal/src/main/webapp/package.json
- portals/devportal/src/main/webapp/source/Tests/setupTests.js
> Upgraded react-test-renderer

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Monetization/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/RestAPIMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/ChipInput.js
- portals/publisher/src/main/webapp/source/src/app/components/Shared/LeftMenuItem.jsx
This PR fixes UI styling issues in the Publisher portal after React18 upgrade.
Resolves https://github.com/wso2/api-manager/issues/2509
> Fix UI styling issues in the Publisher portal

- portals/publisher/src/main/webapp/services/login/introspect.jsp
- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/avatar/Avatar.jsx
Fixes https://github.com/wso2/api-manager/issues/2506
> Fix tenant not setting properly in redirect url

- portals/devportal/src/main/webapp/package-lock.json
- portals/devportal/src/main/webapp/package.json
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/CopyAccessTokenStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateAccessTokenStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/GenerateKeysStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/SubscribeToAppStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/Wizard.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/Details.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
> Add react test renderer and downgrade graphiql

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx
$subject
Preview After the fix.
Related issue: https://github.com/wso2/api-manager/issues/2519
> Fix operation scope auto complete

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
> Fix business plan option missing in UI for mtls

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/ProductResources.jsx
- This PR adds a fix to overcome the loading issue of the API Products Overview page
- Related Issue: https://github.com/wso2/api-manager/issues/2523
- The initialisation of the theme variable within the component had to be fixed
> Fix API Products Overview Page Loading Issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
This will fix the API resource operation selection issue
- https://github.com/wso2/api-manager/issues/2528
> Fix API resource operation selection issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- This PR adds a fix to overcome the loading issue of the API Products Deployments page
- Related Issue: https://github.com/wso2/api-manager/issues/2536
>  Fix API Products Deployments Page Loading Issue 

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Create.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/View.jsx
Related issue: https://github.com/wso2/api-manager/issues/2532
> Fix api docs not save issue and not view issue

- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/Policies.tsx
- $Subject
- Resolves: https://github.com/wso2/api-manager/issues/2524
> Fix styling issues in the add new global policy page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
This will fix the API Product deployment issue
- https://github.com/wso2/api-manager/issues/2537
> Fix API Product deployment issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/QueryComplexityView.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/QueryAnalysis.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/QueryAnalysis/UpdateComplexity.jsx
- Fix several issues in [1]
- Publisher portal misalignment in `API Configurations -> Runtime -> Query Analysis` : https://github.com/wso2/api-manager/issues/2539#issue-2162590443
- Devportal complexity analysis tab misalignment : https://github.com/wso2/api-manager/issues/2539#issuecomment-1972504242
[1] - https://github.com/wso2/api-manager/issues/2539
> Fix styling issues related GraphQL APIs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/APICreateProductBase.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEditWorkspace.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
This PR fixes UI issues in the Publisher portal.
Resolves https://github.com/wso2/api-manager/issues/2535
Resolves https://github.com/wso2/api-manager/issues/2542
> Fix UI issues in the Publisher portal

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/WaitingForApproval.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/HeaderOriginal.jsx
This PR fixes https://github.com/wso2/api-manager/issues/2522 and https://github.com/wso2/api-manager/issues/2550
> Fix console log printing on publisher and workflow page approval issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Fix: https://github.com/wso2/api-manager/issues/2533
Preview After Applying the fix:
> Fix Deployment Page Alignment Issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APICategories.jsx
$subject
Resolves Fix https://github.com/wso2/api-manager/issues/2559
> Fix an issue in the API Categories

- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/Subscriptions.jsx
Fix https://github.com/wso2/api-manager/issues/2515
> Improve Subscription Error Handling

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/BusinessInformation/BusinessInformation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
Fixing : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5635
Related PR: https://github.com/wso2-support/apim-apps/pull/211
> Improve error alerts to display error returned by backend

- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
This PR fixes the banner display issue.
> [Main] Fix banner display issue

- pom.xml
- portals/admin/pom.xml
- portals/devportal/pom.xml
- portals/pom.xml
- portals/publisher/pom.xml
> Prepare 9.0.x version range

- portals/admin/src/main/webapp/services/login/idp.jsp
- portals/devportal/src/main/webapp/services/login/idp.jsp
- portals/publisher/src/main/webapp/services/login/idp.jsp
As part of https://github.com/wso2/api-manager/issues/2496 add support to use JWT tokens for the portals.
> Set JWT for portal login

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
This will fix the issue reported in https://github.com/wso2/api-manager/issues/2557
closing https://github.com/wso2/api-manager/issues/2557
> Replace displayName from name in KeyManager alerts

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
Fix for https://github.com/wso2/api-manager/issues/2585
As the fix, added an if check for whether it is a global KM
{{
!isGlobal && ( ......
)}
> Remove KM visibility for global KM

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
- Remove unused variable; securitySchemeType,
> Fix build failures

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- This PR fixes https://github.com/wso2/api-manager/issues/2627
> Use reference variables to keep value of radio buttons

- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/components/ServiceCard.jsx
Related Issue: https://github.com/wso2/api-manager/issues/2586
> Fix service card alignment issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
Fix for https://github.com/wso2/api-manager/issues/2476
> Add check to prevent publishing for pending deployments

- portals/publisher/src/main/webapp/package-lock.json
- portals/publisher/src/main/webapp/package.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/asyncApiUI/AsyncApiUI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/DescriptionEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/Tags.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Edit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/MarkdownEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/Topics.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/TenantAutocomplete.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/RestAPIMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Listing/Listing.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Listing/Listing.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/ChipInput.js
This PR fixes the following UI issues.
- https://github.com/wso2/api-manager/issues/2579
- https://github.com/wso2/api-manager/issues/2626
- https://github.com/wso2/api-manager/issues/2593
- https://github.com/wso2/api-manager/issues/2568
- https://github.com/wso2/api-manager/issues/2567
- https://github.com/wso2/api-manager/issues/2622
- https://github.com/wso2/api-manager/issues/2608
- https://github.com/wso2/api-manager/issues/2598
- https://github.com/wso2/api-manager/issues/2566
- https://github.com/wso2/api-manager/issues/2660
Resolves https://github.com/wso2/api-manager/issues/2579, https://github.com/wso2/api-manager/issues/2626, https://github.com/wso2/api-manager/issues/2593, https://github.com/wso2/api-manager/issues/2568, https://github.com/wso2/api-manager/issues/2567, …
> Fix UI issues in the portals

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfiguringDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/CommonPolicies/DeletePolicy.jsx
- portals/publisher/src/main/webapp/source/src/app/components/CommonPolicies/Listing.jsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/PolicyConfiguringDrawer.tsx
Fix: https://github.com/wso2/api-manager/issues/2540
> Fix policies button align issue

- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
$subject
- https://github.com/wso2/api-manager/issues/1583
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2233
- https://github.com/wso2-support/apim-apps/pull/103
> Improve: API Context Validation

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/Steps/ValidationResults.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/Overview.jsx
> Fixes issues in the Publisher UI

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
Fixes: https://github.com/wso2/api-manager/issues/2650
> Fix: Doc Type "Other" issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Credentials.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewSecret.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/ChipInput.js
Fixes;
- https://github.com/wso2/api-manager/issues/2640
- https://github.com/wso2/api-manager/issues/2546
- https://github.com/wso2/api-manager/issues/2692
Resolves https://github.com/wso2/api-manager/issues/2640, https://github.com/wso2/api-manager/issues/2546, https://github.com/wso2/api-manager/issues/2692
> Fix issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/operationUtils.js
- portals/publisher/src/main/webapp/source/src/app/data/api.js
Fixes https://github.com/wso2/api-manager/issues/2671 , https://github.com/wso2/api-manager/issues/2661
> Fix issues related to OpenAPI 3.1.0

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
Fixes https://github.com/wso2/api-manager/issues/2696
> Fix Subscription page loading issue when multiple tenants are available

- portals/admin/src/main/webapp/source/src/app/components/APISettings/ApisTableContent.jsx
- portals/admin/src/main/webapp/source/src/app/components/APISettings/ListApis.jsx
Related Issue: https://github.com/wso2/api-manager/issues/2610
> Fix change api provider pagination, and input validation issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/LeftMenuItem.jsx
This PR fixes;
- https://github.com/wso2/api-manager/issues/2676
Resolves https://github.com/wso2/api-manager/issues/2676
> Fix issues in the portals

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Edit.jsx
fixes: https://github.com/wso2/api-manager/issues/2609
fixes: https://github.com/wso2/apim-apps/pull/606
> Fix: Save Button not working on update

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Create/CreateScope.jsx
Fixing : https://github.com/wso2/api-manager/issues/2672
> Fix scope field validation issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
Fixes https://github.com/wso2/api-manager/issues/2473
> Fix issue when publishing an API Product

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/ApiChat.jsx
> Handle query params

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/AISearchAssistant.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatInput.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatMessages.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatWindow.jsx
This PR add the validation logic to feature disabled flows.
Validations were added to the following flows:
- Feature enabled, but on-prem key is not provided &#8594; input box where query is typed in is disabled and a warning is shown with a doc link
- Feature disabled &#8594; Chat popup is not shown on devportal visit
> Add feature disabled checks for Marketplace Assistant

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/MetaData.jsx
https://github.com/wso2/api-manager/issues/2481
> Add version to product context

- portals/devportal/src/main/webapp/site/public/css/main.css
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/AISearchAssistant.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatMessages.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatWindow.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/Header.jsx
- fixed message loading issue
- moved apiCall function to AISearchAssistant to keep the loader when minimized.
> Fixed message loading issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- This fixes: https://github.com/wso2/api-manager/issues/2698
> Fix the width of API tile content box

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
This PR removes maxheight property to fix display issues.
> Remove maxHeight property

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/components/LandingMenu.jsx
Fixes : https://github.com/wso2/api-manager/issues/2590
> Fix UI Issues in Publisher Portal when using Chrome in Ubuntu

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Overview.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/SourceDownload.jsx
Added subscription count in the API overview page in the Devportal.
- https://github.com/wso2/carbon-apimgt/pull/12362
> Subscription count fix

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Public fix for https://github.com/wso2/api-manager/issues/2105
> Fix UI Deployment Tooltip Issue

- portals/admin/src/main/webapp/package.json
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Application/Delete.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyAttributes.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/AddOperation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/AWSLambdaSettings.jsx
- portals/publisher/src/main/webapp/source/src/app/components/CommonPolicies/CreatePolicy.tsx
This PR fixes the follwing issues
- Style issues in the "Download Swagger" link in the Devportal API overview.
- https://github.com/wso2/api-manager/issues/2561
- https://github.com/wso2/api-manager/issues/2664
- https://github.com/wso2/api-manager/issues/2637
Resolves https://github.com/wso2/api-manager/issues/2561, https://github.com/wso2/api-manager/issues/2664, https://github.com/wso2/api-manager/issues/2637
> Fixes issues in the portals

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/components/LandingMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/index.jsx
Fixes : https://github.com/wso2/api-manager/issues/2590
> Fix UI Issues in Publisher Portal Landing Page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
Fixes https://github.com/wso2/api-manager/issues/2649
> Fix document validation issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatInput.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/ApiChat.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/components/ApiChatExecute.tsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/components/TextInput/TextInput.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/ApiTryOut/TryOutController.jsx
- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- Fixes https://github.com/wso2/api-manager/issues/2735
- Adds character limitation for messages that are typed in for both API chat and Marketplace Assistant
> Bug fixes and improvements related to AI features

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx
Fixes https://github.com/wso2/api-manager/issues/2570
New UI
> Fixed UI Styling Issues in API Security Audit Report Viewing Page

- portals/devportal/src/main/webapp/source/src/app/components/Shared/ApiTryOut/TryOutController.jsx
$subject
- Related Issues https://github.com/wso2/api-manager/issues/2737, https://github.com/wso2/api-manager/issues/2738
> Fix username, password state not updating for basic auth

- portals/devportal/src/main/webapp/source/src/app/components/Logout.jsx
Fixes https://github.com/wso2/api-manager/issues/2747
> Fix [GraphQL] API Console History showing issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/StarRatingBar.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfigurationWebSocket.jsx
Fix: https://github.com/wso2/api-manager/issues/2742, https://github.com/wso2/api-manager/issues/2755 ,https://github.com/wso2/api-manager/issues/2700,https://github.com/wso2/api-manager/issues/2752
> Fix multiple issues in Devportal and Publisher

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/ApiKeyHeader.jsx
fixes: https://github.com/wso2/api-manager/issues/2718
> Fix: APIKey Header in API Products

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/components/ServiceCard.jsx
This PR fixes the following issues.
- https://github.com/wso2/api-manager/issues/2759
- https://github.com/wso2/api-manager/issues/2727
- https://github.com/wso2/api-manager/issues/2736
Resolves https://github.com/wso2/api-manager/issues/2759, https://github.com/wso2/api-manager/issues/2727, https://github.com/wso2/api-manager/issues/2736
> Fixes issues in the Publisher and Devportal

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/ListKeyManagerUsages.jsx
Fix https://github.com/wso2/api-manager/issues/2744
> Add a null check for retrieved data of key manager usages

- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Dashboard/APICategoriesCard.jsx
- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Dashboard/TasksWorkflowCard.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Environments.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/AdditionalHeaders.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/Comment.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/UpdateWithoutDetails.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/GoTo/RouteMappings.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/Components/PublishWithoutDeploy.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/Components/PublishWithoutDeployProduct.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/OperationPolicy.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfiguringDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyViewForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/AsyncOperation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/GenericOperation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/Operation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/SpecErrors.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/RestAPIMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/PolicyConfiguringDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/data/defaultTheme.js
This PR fixes the following issues.
- https://github.com/wso2/api-manager/issues/2765
- https://github.com/wso2/api-manager/issues/2769
- https://github.com/wso2/api-manager/issues/2766
Resolves https://github.com/wso2/api-manager/issues/2765, https://github.com/wso2/api-manager/issues/2769, https://github.com/wso2/api-manager/issues/2766
> Fix issues in portals

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/AISearchAssistant.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatMessage.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatMessages.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/ChatWindow.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/Header.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/SimilaritySearch.js
- portals/devportal/src/main/webapp/source/src/app/components/Logout.jsx
- clear chat history on logout
- added pre-defined set of responses to avoid unnecessary chat calls
- moved api card below response
> Marketplace assistant

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/AWSLambdaSettings.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/components/TaskState.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/MuiAlert.jsx
subject
Resolves https://github.com/wso2/api-manager/issues/2756
> Fix issues in the publisher portal

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Chat/Header.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/components/ApiChatPoweredBy.tsx
Added the `Experimental` tag to AI features.
- API Chat
- Marketplace Assistant
> Add `Experimental` tag to AI features

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
> Remove client id and client secret visibility toggle

- portals/devportal/src/main/webapp/package-lock.json
- portals/devportal/src/main/webapp/package.json
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/ApiChat.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/components/ApiChatResponse.tsx
> Improve execution result view

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/ApiKeyHeader.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx
> Fix issues in API product auth header

- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/components/ServiceCard.jsx
Resolves https://github.com/wso2/api-manager/issues/2816
> Fix alignment issue in the services page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Resolves https://github.com/wso2/api-manager/issues/2814
> Fix an alignment issue in the publisher

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/AsyncApiConsole/WebhookSubscriptionUI.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Documents/DocList.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/QueryComplexityView.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/LinterUI/LinterUI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
This PR fixes the following issues.
- https://github.com/wso2/api-manager/issues/2779
- https://github.com/wso2/api-manager/issues/2725
- https://github.com/wso2/api-manager/issues/2831
- https://github.com/wso2/api-manager/issues/2840
Resolves https://github.com/wso2/api-manager/issues/2779, https://github.com/wso2/api-manager/issues/2725, https://github.com/wso2/api-manager/issues/2831, https://github.com/wso2/api-manager/issues/2840
> Bug fixing

- portals/devportal/src/main/webapp/source/src/app/components/Applications/ApplicationFormHandler.jsx
$subject
Fix https://github.com/wso2/api-manager/issues/2745
> Added logic to initialize values for all the unhidden custom application attributes

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/ApiChat.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/components/ApiChatResponse.tsx
- portals/devportal/src/main/webapp/source/src/app/data/api.jsx
- Resolves https://github.com/wso2/api-manager/issues/2835
Fixes the issue where page crash when encountered with a CORS issue
> Fix issue where page crashes due to CORs error

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiChat/ApiChat.jsx
- Resolves https://github.com/wso2/api-manager/issues/2835
> Fix API Chat CORs issue

- portals/devportal/src/main/webapp/site/public/locales/en.json
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
This PR will solve the issue of Callback URLs are not accepted as valid URLs when trying to use the regexp in the Devportal Applications.
Fixes : https://github.com/wso2/api-manager/issues/43
> Fix UI issues when adding Regexp in Callback URLs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
Implemented a WorkflowResponse to populate JSON object with a message property. This property will be used to show the message in the UI.
Fixes: https://github.com/wso2/api-manager/issues/2353
> Add workflow reject/approve message

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
Fix https://github.com/wso2/api-manager/issues/2836
Please note that 2 minor issues were identified in the process. Code highlighting is not working in the expanding view and if the error texts are similar, line number coming will be same to the first one.
> Fix the critical UI issues related to https://github.com/wso2/api-manager/issues/2836

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Usage/Usage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Usage/UsageViewResource.jsx
Fixes https://github.com/wso2/api-manager/issues/2863
> Add improvement to show in which revision the scoped resource is used

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/elements.css
This PR fixes the UI alignment issue, and the padding issue of export button in View Generated Documentation for Rest APIs in publisher portal.
Fixes https://github.com/wso2/api-manager/issues/2749
> Fix UI Alignment issue and Export button issue in View Generated Documentation for Rest APIs

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiUI.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/AsyncApiConsole/WebhookSubscriptionUI.jsx
$subject
Fixes https://github.com/wso2/api-manager/issues/2968
> Fix Webhook unsubscribe curl and spacing issues in devPortal

- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/FormDialogBase.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Application/Delete.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Blacklist/Delete.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Custom/Delete.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Subscription/Delete.jsx
This PR fixes background colors in error alerts in the admin portal.
Fixes https://github.com/wso2/api-manager/issues/2982
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Fix alert background color in errors

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
- portals/publisher/src/main/webapp/source/src/app/data/api.js
Fix API Params validation when publisher access control enabled.
> Fix API Params Validation

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
> Add organization sharing in publisher portal

- portals/devportal/src/main/webapp/site/public/css/main.css
- portals/publisher/src/main/webapp/site/public/css/main.css
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/View.jsx
Fixing : https://github.com/wso2/api-manager/issues/3063
> Fix markdown doc styling issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/BackendRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/CommonRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/RequestCountRateLimit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/RequestCountRateLimitUnit.jsx
> Add rate limiting changes and fix form bug

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
> Add endpoint Page changes for AI API

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
- Add tooltip to show subscription policy Details
- Add new query parameter to fetch subscription policies for AI Apis Make API key default for AI APIs in dev portal
> Add subscription policy page changes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/CommonRateLimitingForm.jsx
- Move token based throttling configurations from aiConfigurations to maxTps
> Update RuntimeConfiguration page to support maxTps REST API changes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/BackendRateLimiting.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/BackendRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/CommonRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/RequestCountRateLimit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
> Add EP rate limiting specify change

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
> Fix apikey type

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
> Fix formatting issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
> Fix api key header bug

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/Steps/ProvideAIOpenAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/AIAPIMenu.jsx
> Fix UI naming conventions fo AI APIs

- .github/workflows/main.yml
> Fix git action for UI PRs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
Fixing : https://github.com/wso2/api-manager/issues/3138
> Fix overwritten changes of AI API endpoint config

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
Related PR : https://github.com/wso2/carbon-apimgt/pull/12613/files
> Fix api-key edit of AI API for empty string

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
Fixes https://github.com/wso2/api-manager/issues/3115
> Stopped secret placeholder from overriding the client secret and password in endpoint security

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/SOAPToREST/SOAPToRESTListing.jsx
Fixes: https://github.com/wso2/api-manager/issues/3141
> Fix MonacoEditor causing parent width to grow indefinitely

- portals/admin/src/main/webapp/source/src/app/components/AdvancedSettings/TenantConfSave.jsx
Fixes https://github.com/wso2/api-manager/issues/3176
Fixes part of https://github.com/wso2/api-manager/issues/3140
https://github.com/user-attachments/assets/8a827379-4a7d-44bf-a45e-d0dbac913ab8
> [Bug Fix] Fix Suggestions Not Working While Editing Advanced Configurations

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
Fixes https://github.com/wso2/api-manager/issues/3178
> [Bug Fix] Move the Floating Progress Indicator to Save Button

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/CustomSplitButton.jsx
fixes: https://github.com/wso2/api-manager/issues/3159
> Fix: Sequence Backend UI Issues

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/KeyValidation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Operations/Operation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/src/main/webapp/source/src/app/data/AuthManager.js
This will fix https://github.com/wso2/api-manager/issues/3165
> Fix issue related to add Key Manager form

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AsyncAPI/ApiCreateAsyncAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
Fix the step indicators of Create API forms in publisher portal
Fixes https://github.com/wso2/api-manager/issues/3199
> Fix step indicators of Create API forms

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
> Add apiKeyIdentifierType config

- portals/admin/src/main/webapp/source/src/app/components/Throttling/Subscription/AddEdit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
- Remove required tag from token input fields (total tokens, prompt tokens, completion tokens)
- Change info icon color in the subscription policy listing page of the publisher
> Fix minor UI issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/Steps/ProvideAIOpenAPI.jsx
1. Fix the validation issue in Create AI API Form step 1
2. Mark the two fields as mandatory
Fixes https://github.com/wso2/api-manager/issues/3233
https://github.com/user-attachments/assets/4eddc823-4e3b-4946-8ccd-6fd89667f934
> Fix the validation in Create AI API form

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
Fixes https://github.com/wso2/api-manager/issues/3123
> Fixed issue where endpoint certificate cannot be saved.

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/AttachedPolicyForm/General.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyAttributes.tsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/General.tsx
1. Fix overflow issue in deployment cards
2. Replace native select options with mui components
Fixes https://github.com/wso2/api-manager/issues/3245
**Fix 1:**
**Fix 2:**
> Fix minor UI bugs in deployment cards and select options

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/KeyManagerConfiguration.jsx
Related to: https://github.com/wso2/api-manager/issues/3121
> Fix UI issues with the `Microsoft Graph API Endpoint Version` checkbox

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/Banner.jsx
Fixes https://github.com/wso2/api-manager/issues/3235
Fixes https://github.com/wso2/api-manager/issues/3222
> [Bug Fix] Fix Minor UI Bugs

- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/Subscriptions.jsx
Fixing the UI bug mentioned in the issue
Fixes https://github.com/wso2/api-manager/issues/3255
- Updated the code to use the existing classes
- Removed unused classes
- Updated the design
> Fix the bugs in Subscription Management Dialog Box

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewToken.jsx
Fixes https://github.com/wso2/api-manager/issues/3207
> [Bug Fix] Fix Access Token Message Spacing

- portals/devportal/src/main/webapp/site/public/css/main.css
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Overview.jsx
Fixes https://github.com/wso2/api-manager/issues/3209
https://github.com/user-attachments/assets/662be11d-ed8c-49a4-b566-d5a1a7c1bfe9
> [Bug Fix] Fix Thumbnail Loading Animation

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/Steps/ProvideAIOpenAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GenericEndpoint.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
Refractor the AI API creation
N/A
Updated the UI with the new API payloads and the related logics
> Refactor AI API implementation in Publisher Portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx
Resolves https://github.com/wso2/api-manager/issues/3277
> Fix API audit security page crashing

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/Scopes.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/Policies.tsx
- Resolves https://github.com/wso2/api-manager/issues/3220
- Resolves https://github.com/wso2/api-manager/issues/3242
- Resolves https://github.com/wso2/api-manager/issues/3243
> Fixes issues in portals

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
Resolves https://github.com/wso2/api-manager/issues/3276
> Fix endpoint validation issue with AI APIs

- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/headersearch/SearchUtils.jsx
Fixes https://github.com/wso2/api-manager/issues/3293
The behavior was only observed on publisher portal while typing a search query. Added a missed conditional check
https://github.com/user-attachments/assets/dfbca870-3621-4e02-baf3-c254c1abe37b
> [Bug Fix] Fix Publisher Attribute Search

- portals/admin/src/main/webapp/source/src/app/components/APICategories/ListApiCategories.jsx
- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Dashboard/APICategoriesCard.jsx
- portals/admin/src/main/webapp/source/src/app/components/TenantTheme/UploadTheme.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Advanced/HelpLinks.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Application/List.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Blacklist/List.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Custom/List.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Subscription/List.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/APIRevisionDeployment.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/APIStateChange.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/ApplicationCreation.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/ApplicationDeletion.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/RegistrationCreation.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/SubscriptionCreation.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/SubscriptionDeletion.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/SubscriptionUpdate.jsx
- portals/admin/src/main/webapp/source/src/app/components/Workflow/UserCreation.jsx
- portals/publisher/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/Onboarding.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Subscription/SubscriptionCreation/SubscriptionCreation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Subscription/SubscriptionUpdate/SubscriptionUpdate.jsx
Fixing the broken help Urls
Fixing the outdated redirections
Fixes https://github.com/wso2/api-manager/issues/3280
Added the docUrl to the publisher config
Updated the URLs
N/A
> Update the help urls to prevent outdated redirections

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/CustomBackend.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/CustomSplitButton.jsx
fixes: https://github.com/wso2/api-manager/issues/3278
> Fix: Save and Deploy Button Issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
> Append Bearer for MistralAI and OpenAI APIs

- portals/admin/src/main/webapp/source/src/app/components/AiVendors/AddEditAiVendor.jsx
- portals/admin/src/main/webapp/source/src/app/components/AiVendors/DeleteAiVendor.jsx
- portals/admin/src/main/webapp/source/src/app/components/AiVendors/ListAiVendors.jsx
- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
Introduce support for an `unsecured` authentication configuration to enable open access for LLM services within the Admin Portal's AI/LLM configuration settings.
> Add `unsecured` auth configuration

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
Resolves the issue where Endpoints page Save button remains active when API Key is not provided
> Fix Endpoints page Save button active isseu  when API Key is not provided

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/LoadBalanceConfig.jsx
Fix: https://github.com/wso2/api-manager/issues/3197
> Fixing issue when use default sessionTimeOut

- portals/admin/src/main/webapp/WEB-INF/web.xml
- portals/admin/src/main/webapp/services/login/login_callback.jsp
- portals/admin/src/main/webapp/services/refresh/refresh.jsp
- portals/admin/src/main/webapp/source/dev/auth_login.js
- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/ListBase.jsx
- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ActionConfigDialog.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/DeletePolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/index.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/AddEditRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/CreateOptionsModal.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/DeleteRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/index.jsx
- portals/admin/src/main/webapp/source/src/app/data/APIClientFactory.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPIClient.js
- portals/admin/src/main/webapp/source/src/app/data/Utils.js
- Implementing the governance ruleset and policy management dashboard
- Added the routes
- Implemented the API client
- Updated the listbase to allow more customizations
- Implemented the following pages
- View Governance Policies
- Create/Edit Governance Policy
- View Governance Rulesets
- Create/Edit Governance Ruleset
> Implement Policy and Ruleset management views

- portals/admin/src/main/webapp/package-lock.json
- portals/admin/src/main/webapp/package.json
- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/Summary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/index.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ActionConfigDialog.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/DeletePolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/index.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/data/APIClientFactory.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
Implementing the pages that shows the governance results
- Added mui/x-charts dependency to use for the charts
- Implemented the pages
> Implement governance results pages

- portals/admin/src/main/webapp/source/src/app/components/Throttling/Subscription/List.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
- tests/cypress/fixtures/api_artifacts/advanceConfigFalse.json
- tests/cypress/fixtures/api_artifacts/advanceConfigTrue.json
- tests/cypress/fixtures/api_artifacts/tenant-conf.json
- tests/cypress/integration/admin/03-add-edit-delete-subscription-throttle-policies.spec.js
- tests/cypress/integration/publisher/011-lifecycle/01-block-demote-to-created-depricate-api.spec.js
- tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
- tests/cypress/support/commands.js
- This PR fixes several UI test failures
- This PR also fixes https://github.com/wso2/api-manager/issues/3556
> Fix UI Test Failures

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/ExternalStores/ExternalStores.jsx
- Fix external devportal page crashing when reloading
- Fixes: https://github.com/wso2/api-manager/issues/3301
> Fix External Devportal Page Crashing Issue

- portals/admin/src/main/webapp/services/login/login_callback.jsp
- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/Summary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ActionConfigDialog.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/RulesetSelector.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/AddEditRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/components/Shared/DonutChart.jsx
- portals/admin/src/main/webapp/source/src/app/data/Constants.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPIClient.js
- portals/admin/src/main/webapp/source/src/app/data/Utils.js
- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RuleViolationSummary.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/publisher/src/main/webapp/source/src/app/data/Utils.js
- Resolving the [issues discussed in the demo](https://docs.google.com/document/d/1Q8-Zz-XauZ3dZQ8qmS4rFeDckT3UoZFhGBEtBKzHqSc/edit?tab=t.0)
- Fixing other TODOs
- Added new ruleset selector component
- Integrated the label feature
- Updated the API calls with the latests changes
> Add UI Improvements to the Governance feature

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
> Fix subscriptions page not rendering issue

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/GatewayConfiguration.jsx
- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/GatewayFeatureCatalogContext.js
- This PR, adds a dropdown in `Add Gateway` view to select the gateway type. (Earlier there was a radio button group to select between APK and Regular)
> Admin UI changes to onboard external gateways

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfigurationWebSocket.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/RestAPIMenu.jsx
> [Gateway Federation][Feature][4.5.0][PR2] Add Publisher UI Restrictions for Federated Gateway Types Using a Templated JSON

- portals/admin/src/main/webapp/services/logout/logout_callback.jsp
- portals/admin/src/main/webapp/services/refresh/refresh.jsp
- portals/publisher/src/main/webapp/services/logout/logout_callback.jsp
- portals/publisher/src/main/webapp/services/refresh/refresh.jsp
Fixing the login issue that occurs when using tenants
Updated the cookie name
> Correct the cookie name in logout callbacks

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/OrganizationSubscriptionPoliciesManage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
- Resolves https://github.com/wso2/api-manager/issues/3586
- Remove organization feature related UI changes for API prodcuts
- Remove organization name for organization policies to adhere the REST API changes
- Fix styling issues
> Fix multiple issues related to organization feature UI

- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/DeletePolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/RulesetSelector.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/AddEditRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/data/Constants.js
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RuleViolationSummary.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/components/TaskState.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/Governance/GovernanceViolations.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
- portals/publisher/src/main/webapp/source/src/app/data/Utils.js
- Load the API Update action configuration by default in create policy view
- UI/UX improvements in label select field
- Added pagination to rule violation summary
- Fix error handling in blocking scenarios
- Added error message column to rule violation table (blocking scenarios)
- Handle displaying unapplied rulesets in compliance view
- Method naming improvements
- Displayed ruleset types and api details in compliance view
> Add minor improvements to the governance pages

- tests/cypress/integration/publisher/017-api-policies/01-api-specific-policy.spec.js
- tests/cypress/integration/publisher/019-read-only-user/00-verify-that-read-only-user-cannot-create-update-api.spec.js
UI test modifications for https://github.com/wso2/api-manager/issues/3109
> Modify UI tests for the policy fix

- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/ListBase.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/data/AuthManager.js
- portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ListBase.jsx
- $subject + other minor improvements
- Fixing the issue with label attaching
- Rename applicability to attachment
- Add text wrapping to table descriptions
- Add missing auth manager condition
> Use label ids instead of label names for policy creation

- portals/publisher/src/main/webapp/source/src/app/data/api.js
Change tag to 'API Design Assistant
> Change tag to 'API Design Assistant'

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
This PR fixes the issue where policy list is not rendering due to a filtering logic issue.
> Fix issue where policy list is not rendering within the Policy page

- portals/admin/src/main/webapp/source/dev/auth_login.js
- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/ListBase.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ActionConfigDialog.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/AddEditRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/data/Constants.js
- portals/admin/src/main/webapp/source/src/app/data/Utils.js
- portals/publisher/src/main/webapp/services/dev_proxy/auth_login.js
- portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ListBase.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RuleViolationSummary.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/Governance/GovernanceViolations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/Governance/GovernanceViolationsSummary.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
- portals/publisher/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/publisher/src/main/webapp/source/src/app/data/Utils.js
Multiple UI improvements and bug fixes
- Handle pending and unapplied states in progress bars
- Disable sorting in path, message and description columns in RuleViolationSummary
- Conditionally render compliance page based on API type (Compliance page will be not displayed in API products, GraphQL, SOAP APIs)
- Add download functionality for ruleset content [1]
- Limit description field height in AddEditPolicy
- Display compliance results with pending policies. Now the compliance view will display the completed results even when there are pending policy evaluations. [2]
- Added info alert for API Create and Update actions in ActionConfigDialog [3]. Fixes https://github.com/wso2/api-manager/issues/3598 as well with 76007b9.
- Updated the blocking notification in overview page publish action …
> Multiple UI improvements and bug fixes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APIProduct/APIProductCreateWrapper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AsyncAPI/ApiCreateAsyncAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/WSDL/ApiCreateWSDL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
This PR addresses multiple bug fixes related to gateway federation-related publisher UIs.
- Resolves https://github.com/wso2/api-manager/issues/3607
- Resolves https://github.com/wso2/api-manager/issues/3606
- Resolves https://github.com/wso2/api-manager/issues/3602
> [UI][BUG-FIXES] Fix Issues in Gateway Federation Related UIs

- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
Check whether the user is logged at component mount, call the API to get the user organization name and save it in the session storage. This stored item will be retrieved and shown at the page render.
Fixes https://github.com/wso2/api-manager/issues/3611
> Fix devportal auth issue before login

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/ListGWEnviornments.jsx
- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- tests/cypress/integration/admin/00-add-edit-delete-microgateway-environments.spec.js
This PR,
- Fixes issues with adding multiple vhosts to a gateway environment
- adds data-testid attributes to new elements
- Fixes `Add Edit Delete Microgateway Environments` admin UI test case
> Add UI Improvements

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpoints/AddEditAIEndpoint.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelFailover.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelRoundRobin.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelWeightedRoundRobin.tsx
Improving the UI/UX of AI endpoints and policies page
- Improve error handling and validation of Endpoints page
- Improve UI of policy drawer
> Improve error handling of AI endpoints page

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
Fixes https://github.com/wso2/api-manager/issues/3686
https://github.com/user-attachments/assets/1cafdc5c-a09a-4282-bbcc-8052f7480c44
> Populate custom GW default hostname template by default

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpoints/AddEditAIEndpoint.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelFailover.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelRoundRobin.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelWeightedRoundRobin.tsx
- This PR fixes the issue where endpoint creation, update, and deletion were blocked for users with internal/creator role.
- For AI Policies, remove the default suspendDuration and requestTimeout fields if not specified via the UI.
- https://github.com/wso2/api-manager/issues/3684
> Intra-vendor model routing feature improvements

- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/Summary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/index.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Overview/Summary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ActionConfigDialog.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/AddEditPolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/DeletePolicy.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/AddEditRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/DeleteRuleset.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/components/Shared/DonutChart.jsx
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/SampleAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/DonutChart.jsx
Multiple UI improvements and bug fixes to governance dashboards
- Update compliance chart colours (Fixes https://github.com/wso2/api-manager/issues/3653)
- Rename overview to compliance dashboard
- Remove duplicate values from chart tooltips
- Improve error handling in delete policy and ruleset
- Remove the link from policy adherence table (Temporarily Fixes https://github.com/wso2/api-manager/issues/3695)
- Display ruleset validation errors (Fixes https://github.com/wso2/api-manager/issues/3692)
- Fix the continue button SampleAPI deploymentcomponent (Fixes https://github.com/wso2/api-manager/issues/3678)
- Multiple improvements to action config UI (Fixes https://github.com/wso2/api-manager/issues/3651)
- Add server side pagination for listing rulesets/policies (Fixes …
> UI Improvements to Governance Dashboards

- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/ListBaseWithPagination.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
- portals/admin/src/main/webapp/source/src/app/data/GovernanceAPI.js
- portals/publisher/src/main/webapp/source/src/app/components/Addons/Addons/ListBase.jsx
$subject
Fixes https://github.com/wso2/api-manager/issues/3715
- Created a new ListBase component for utilizing server side pagination
- Updated the api calls
- Added minor improvements to the table loading and empty states
> Utilize server side pagination in Compliance pages

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/ShareAPI/OrganizationSubscriptionPoliciesManage.jsx
- Partial fix for https://github.com/wso2/api-manager/issues/3740
- This PR fixes the issue where subscription policies can not be selected for shared organizations for Async APIs.
> [B2B] Fix subscription policy selection issue for async APIs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/DesignAssistantMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/components/LandingMenu.jsx
> Revert "Fix publisher landing page UI"

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/TopMenu.jsx
Fix: https://github.com/wso2/api-manager/issues/3746
> Make API Design Assitant only availalbe to users with apim:api_create scope

- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/Compliance.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/RuleViolationSummary.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/PolicyAdherenceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Shared/DonutChart.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/PolicyAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RuleViolationSummary.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/RulesetAdherenceSummaryTable.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/DonutChart.jsx
- Change the structure of the API Compliance UI
- Optimize the UI by reducing the API calls
- Added the rule adherence chart
- Fix the loading states (If all policies are pending, only the policy adherence table will be showed)
- Updated the progress bar colours
- Optimize the UI by reducing the API calls
https://github.com/user-attachments/assets/9f5e3268-2971-4dde-a57a-28af1d006ae2
> Change the structure of the API Compliance UI

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpoints/EndpointCard.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelFailover.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelRoundRobin.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelWeightedRoundRobin.tsx
- Resolves: https://github.com/wso2/api-manager/issues/3677
> [Intra-vendor Model Routing] Fix AI API policy configuration related bugs

- .github/workflows/main.yml
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/Steps/ProvideGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
- Resolves: https://github.com/wso2/api-manager/issues/3723
- Resolves: https://github.com/wso2/api-manager/issues/3663
> Fix issue where multiple validation calls are getting fired when URL import option is used

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
$subject
Fixes [#api-manager#3679](https://github.com/wso2/api-manager/issues/3679)
- Updated the selected card's border colour
- Made the gateway cards field have full width of the container
> Fix responsiveness issues in gateway cards

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/APICreateWithAI.jsx
Update graphql sample query card to 'Create a GraphQL API to query patient data'
> Update graphql sample query card

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
Fixes https://github.com/wso2/api-manager/issues/3634
> Fix an issue when import and editing a swagger definition

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AsyncAPI/ApiCreateAsyncAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/APICreateWithAI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/components/AlertDialog.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
Fixes https://github.com/wso2/api-manager/issues/3733
> Fix GW selection issue in API Design Assistant flow

- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/APICompliance/Compliance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APICompliance/Compliance.jsx
$subject
+ Changing the compliance icon
Display a notification when no policies have been attached
Admin portal:
Publish portal:
> Handle the scenario where gov policies are not attached the API

- portals/admin/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/site/public/conf/settings.json
- Fix doc links for APIM 4.5.0 Release
> Fix Doc Links for APIM 4.5.0 Release

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AsyncAPI/ApiCreateAsyncAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/ApiCreateOpenAPI.jsx
> Fix issue in publisher

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/ListGWEnviornments.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/Permission.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Permission.jsx
Resolves: https://github.com/wso2/api-manager/issues/3765
Below are the screenshots of the UI after the changes.
> Fix the issues in visibility permissions view in admin portal and publisher portal

- portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/ApiComplianceTable.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/DeleteRuleset.jsx
This pull request includes changes to improve the display of API compliance information and enhance error handling in the Governance dashboard of the admin portal. The most important changes are listed below:
Improvements to API compliance display:
* [`portals/admin/src/main/webapp/source/src/app/components/Governance/ComplianceDashboard/ApiComplianceTable.jsx`](diffhunk://#diff-fa0d1dc52ee38db095abb395f5f96cd6b242489301dd186d3b029d0eaa1220cbL168-R168): Updated `customBodyRender` to include the API version in the display text.
Enhancements to error handling:
* [`portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/DeleteRuleset.jsx`](diffhunk://#diff-6f99d20fd203785c8f9e7b1e077fc585ef09cdad17768d7b9907eac32909f619L48-L51): Improved error handling by checking …
> Fix Governance Minor Bugs

- portals/admin/src/main/webapp/source/src/app/components/Governance/Policies/ListPolicies.jsx
- portals/admin/src/main/webapp/source/src/app/components/Governance/RulesetCatalog/ListRulesets.jsx
Refactor governance tables to pass apiCall to ListBase
Removed intial data and reused the api call prop
N/A
> Refactor governance tables to pass apiCall to ListBase

- tests/cypress/integration/publisher/001-api-create/02-create-api-with-swagger-file-super-tenant.spec.js
- tests/cypress/integration/publisher/001-api-create/03-create-api-with-swagger-url-super-tenant.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/00-lint-when-creating-api-with-swagger-url.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/01-lint-when-creating-api-with-swagger-file.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/02-lint-when-creating-api-with-swagger-v2-url.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/03-lint-when-creating-api-with-swagger-v2-file.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/04-lint-when-creating-api-with-errornous-swagger-file.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/05-lint-when-editing-before-import.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/06-lint-when-importing-api-with-swagger-url.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/07-lint-when-importing-api-with-swagger-file.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/08-lint-when-importing-api-with-swagger-v2-url.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/09-lint-when-importing-api-with-swagger-v2-file.spec.js
- tests/cypress/integration/publisher/021-api-linter-feature/10-lint-when-importing-api-with-errornous-swagger-file.spec.js
The following test cases were fixed.
- publisher/001-api-create/02-create-api-with-swagger-file-super-tenant.spec.js
- publisher/001-api-create/03-create-api-with-swagger-url-super-tenant.spec.js
- publisher/021-api-linter-feature/00-lint-when-creating-api-with-swagger-url.spec.js
- publisher/021-api-linter-feature/01-lint-when-creating-api-with-swagger-file.spec.js
- publisher/021-api-linter-feature/02-lint-when-creating-api-with-swagger-v2-url.spec.js
- publisher/021-api-linter-feature/03-lint-when-creating-api-with-swagger-v2-file.spec.js
- publisher/021-api-linter-feature/04-lint-when-creating-api-with-errornous-swagger-file.spec.js
- publisher/021-api-linter-feature/05-lint-when-editing-before-import.spec.js
- publisher/021-api-linter-feature/06-lint-when-importing-api-with-swagger-ur …
> Fix issues in UI tests

- tests/cypress/integration/publisher/020-prototyped-apis/00-try-out-resources-without-key-when-security-disabled.spec.js
- Fix a UI test failure related to `00-try-out-resources-without-key-when-security-disabled.spec.js`
> Fix a UI Test Failure

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Sdk.jsx
Fixes https://github.com/wso2/api-manager/issues/3288
> Separate the search bar from the title in SDK page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Properties/EditableRow.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Properties/Properties.jsx
- Fix https://github.com/wso2/api-manager/issues/3771
> Fix multiple issues in API properties page

- portals/admin/src/main/webapp/source/src/app/components/Throttling/Advanced/AddEditExecution.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Application/AddEdit.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Subscription/AddEdit.jsx
UI fix for : https://github.com/wso2/api-manager/issues/3764
> Add UI validation to prevent negative values for default quota limits in throttling policies

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
This change disables the Publish button in the publisher portal Overview page when mandatory API properties are not provided for that particular API.
Retrieve the required custom properties if configured.
Retrieve the additional properties added for the particular API.
Check whether the required props are present and their values are not empty. If not disable the Publish button with an info tooltip.
Related issue: https://github.com/wso2/api-manager/issues/3568
> Disable publish button in Overview page when mandatory props not provided

- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Apis.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
Address comments for the following PRs,
- https://github.com/wso2/apim-apps/pull/851
- https://github.com/wso2/apim-apps/pull/880
> Address Comments For Some PRs

- tests/cypress/integration/publisher/013-api-product/06-download-api-product.spec.js
- $Subject
- Related Issues: https://github.com/wso2/api-manager/issues/2430
> Add UI tests for API product download

- portals/admin/src/main/webapp/source/src/app/components/AiVendors/AddEditAiVendor.jsx
- portals/admin/src/main/webapp/source/src/app/components/AiVendors/ListAiVendors.jsx
This PR fixes minor issues in the license header to ensure consistency and compliance.
https://github.com/wso2/apim-apps/pull/741
> Fix minor issues in license header

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
Following the change in https://github.com/wso2/apim-apps/pull/998 there was a UI issue when trying to create an API Product. This PR fixes that issue.
> Fix issue with creating API Products

- portals/admin/src/main/webapp/site/public/locales/en.json
- portals/admin/src/main/webapp/site/public/locales/fr.json
This PR adds the missing localization string for the application update workflow.
> Add missing localization string for the application update workflow

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/GatewayConfiguration.jsx
This PR adds radio button support for gateway connector configs.
> Add radio button support for gateway connector configs

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/Certificates.jsx
- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/KeyManagerConfiguration.jsx
Fixing https://github.com/wso2/api-manager/issues/4081
Related feature issue: https://github.com/wso2/api-manager/issues/3913
Refactored the component by removing the useCallback hooks etc.
TBD
> Support nested authConfigurations under KM configurations

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
Fix try out page not loading issue
> Fix try out page not loading issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
This PR refactors the function written to validate mandatory properties of an API by removing redundant variables and handling them by setting states.
> Refactor mandatory prop validation function

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/Comment.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/CommentAdd.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/CommentReply.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Comments/Comments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/MCPServers/Create/Steps/ExistingAPIToolSelection.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Comments.js
Add changes to support MCP server comments.
- Related issue: https://github.com/wso2/api-manager/issues/3978
> [MCP] Improvements to `Comments` page of MCP Servers

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/DocThumb.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
Fixing several minor bugs in the publisher/developer portal cards.
- Prevent displaying the API Product chip in devportal cards
- Fixed the links of documentation cards in devportal search results
N/A
> Fix minor issues in API Cards

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Download.jsx
The purpose of this PR is to:
- fix https://github.com/wso2/api-manager/issues/4317
- fix https://github.com/wso2/api-manager/issues/4316
- https://github.com/wso2/api-manager/issues/4351
- Disable the Create button if the document is not uploaded
- Improved styling of the create document form
- Prevent auto downloading the document files in background
- Fixed the crashing doc create page
https://github.com/user-attachments/assets/d9f89ba3-d8fa-495f-ac4b-356b602fc820
> Fix multiple bugs in Documents Page

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/LetterGenerator.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/LetterGenerator.jsx
- portals/publisher/src/main/webapp/source/src/app/components/PublisherLanding/APIProductSection.jsx
- Resolves: https://github.com/wso2/api-manager/issues/4124 and issue 3 under https://github.com/wso2/api-manager/issues/4369
- Resolves issue 2 under https://github.com/wso2/api-manager/issues/4369
- Resolves issue 4 under https://github.com/wso2/api-manager/issues/4369
- Resolves issue 5 under https://github.com/wso2/api-manager/issues/4369
> Fix issue where MCP Playground connect button remains active when not deployed

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/ProductResources/ProductResourcesEditWorkspace.jsx
This PR adds fixes for the following issues.
1. Need to restrict revision deployment for read only Gateway Environments.
2. Restrict retire API for discovered APIs from the UI.
3. Need to fix showing name instead of displayName for listed APIs during product creation.
> Fix bugs related to Publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Create/CreateScope.jsx
Fix: https://github.com/wso2/api-manager/issues/4055
> Set scope validation when onBlur call
