wso2/apim-apps

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
Adding UI validation for API properties Key value.
1. Property name should not contain spaces or any white space characters.
2. Property name cannot be any of the following reserved keywords: _**provider, version, context, status, description, subcontext, doc, lcstate, name, tags.**_ (In both lower and upper case keywords should be restricted)
This PR will add the above validations in the publisher portal UI.
Fixes: https://github.com/wso2/product-apim/issues/11219 
**1. Uppercase validation for Keywords**
**2. Whitespace validation**
> Add UI validation to API properties with spaces and upper case keywords

- portals/admin/source/src/app/ProtectedApp.jsx
To fix showing the error message: Admin Portal UnAuthenticated Request error.
Fixes: https://github.com/wso2/product-apim/issues/11394
Pass the base64 encoded username to the back-end when calling to get tenant-info.
> Add fix to base64 encode username before passing to back-end

- portals/publisher/source/src/app/components/Apis/Details/Properties/Properties.jsx
Fixes Issue of not recognizing "lcState" as Keyword
> Change keywords to lowercase

- portals/admin/source/src/app/components/Throttling/Advanced/AddEdit.jsx
Fixes: https://github.com/wso2/product-apim/issues/11410
Underscores should be allowed in throttling policy names since they are quite common in naming conventions.
Changed the frontend regular expression for throttling policy name.
- https://github.com/wso2/carbon-apimgt/pull/10667
> Changing the frontend regular expression for throttling policy name

- portals/devportal/source/src/app/components/Applications/ApplicationFormHandler.jsx
- portals/devportal/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- Resolves https://github.com/wso2/product-apim/issues/12152
When the application owner is switched through the admin portal, but with no consideration on the case sensitivity, the devportal behaves as though this username is case sensitive. Hence, the actual app owner is unable to edit/delete this app. This PR fixes this application owner mismatch occurring due to case sensitivity. All owner usernames are hereby considered to be case insensitive.
With this fix, when the owner is switched while disregarding the case sensitivity, that owner is able to edit and delete that said application.
> Fix app owner mismatch occurring due to case sensitivity

- portals/devportal/source/src/app/components/Apis/Details/Documents/Documents.jsx
As $subject, this fix will sort the document list before showing it in the dev portal.
- https://github.com/wso2/product-apim/issues/12192
> Add document sort function to the dev portal

- portals/devportal/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
Fixes https://github.com/wso2/product-apim/issues/12300
- API With Gateway URLs visibility enabled(Gateway section is displayed)
- API With Gateway URLs visibility disabled(Gateway section is not displayed) and Blank Page issue resolved.
> Adding null check for URLs for gateway urls visibility disabled scenario

- portals/publisher/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/source/src/app/components/Apis/Details/Resources/components/AsyncOperation.jsx
- Fixes https://github.com/wso2/product-apim/issues/12210
- When updating an Async API definition the corresponding API and API product in Solace is updated. This update can be performed through **Topics** and **AsyncAPIDefintion** panel
- Even after just saving the API definition, a use can navigate to deployment panel and deploy the current snapshot to the Solace using **Deploy New Revision** method. 
- https://github.com/wso2/carbon-apimgt/pull/11012
> Add UI components for updating solace definition

- portals/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiConsole.jsx
- portals/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiUI.jsx
- portals/devportal/source/src/app/components/Apis/Details/AsyncApiConsole/GenericSubscriptionUI.jsx
This PR hides 'Generate CURL' section in tryout page for unsupported API types.
> Hide generate CURL section in TryOut for unsupported types

- portals/publisher/source/src/app/data/defaultTheme.js
To update the analytics link in publisher UI to `https://console.choreo.dev/`.
- Resolves https://github.com/wso2/product-apim/issues/12374
> Update analytics link in publisher UI

- portals/publisher/site/public/conf/settings.js
- portals/publisher/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
This PR fixes part of https://github.com/wso2/product-apim/issues/11500 with default support for json, yaml and md files through UI.
> Add support to add json yaml and md type documents

- portals/publisher/source/src/app/components/Base/index.jsx
- portals/publisher/source/src/app/components/Shared/Alert.jsx
Fixes https://github.com/wso2/product-apim/issues/12452
Color theme and font of the message boxes that appear when an API state was changed, API was updated, etc. is not compatible with the existing portal theme.
Font, Font size and the color of the Toasts
Loading Toast is in blue and Success Toast is in Green:
> Change Toast message theme in publisher

- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Policies/AttachedPolicyCard.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/DeletePolicy.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/DraggablePolicyCard.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyViewForm.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/SourceDetails.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/SaveOperationPolicies.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/Types.d.ts
- portals/publisher/source/src/app/components/Apis/Details/Policies/ViewPolicy.tsx
- portals/publisher/source/src/app/components/CommonPolicies/ViewPolicy.tsx
UI changes needed for [1].
This PR adds the capability to handle the migration from `Mediation Policy` to `Operation Level Policy`.
- When a migrated API has an already attached mediation policy, it is shown in the policies UI.
- Attached policy is not configurable, but is free to delete if see fit.
- Upon the first `Save`, they fall back to the normal behavior (i.e. can download and configure policy)
Also, fixes the following bug:
- Removes redundant API calls being made for policy download. With the fix added by this PR, just the single API call is made for policy download.
1. https://github.com/wso2/product-apim/issues/12566
> [Operation Level Policy Support] Improvements and bug fixes - 04

- portals/publisher/package-lock.json
- portals/publisher/package.json
- portals/publisher/site/public/conf/settings.js
- portals/publisher/site/public/locales/en.json
- portals/publisher/site/public/locales/raw.en.json
- portals/publisher/source/src/app/components/Apis/Details/Policies/CreatePolicy.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyDropzone.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/SourceDetails.tsx
- portals/publisher/source/src/app/components/Apis/Details/Policies/PolicyForm/UploadPolicyDropzone.tsx
- portals/publisher/source/src/app/components/CommonPolicies/CommonPolicies.tsx
- portals/publisher/source/src/app/components/CommonPolicies/CreatePolicy.tsx
- portals/publisher/source/src/app/components/CommonPolicies/Listing.jsx
- portals/publisher/source/src/app/components/CommonPolicies/ViewPolicy.tsx
- portals/publisher/source/src/app/data/api.js
With this PR, the policy create and view capabilities have been extended to support Choreo Connect gateway. Major changes include:
- When creating a new policy (common policy / API specific policy), now you can also upload the CC related policy definition file. With this change you can either upload policy files for both gateways or just a single gateway.
- Also, when viewing a policy, you can see CC related details in the same form which previously existed.
> [Operation Level Policy Support] Extend policy create and view capabilities for CC

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
making the default selection of grants to password and client credentials only for other KM types
> making the default selection of grants to password and client credentials only for other KM types

- portals/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx
This PR fixes custom policies link being shown to tenant admins issue in the rate limiting card in admin portal.
Fixes https://github.com/wso2/product-apim/issues/12799
> Fix custom policies shown for Tenant admins issue

- portals/admin/site/public/conf/settings.js
- portals/admin/source/src/app/components/AdminPages/Dashboard/Dashboard.jsx
- portals/admin/source/src/app/components/Base/Navigator.jsx
- portals/admin/source/src/app/data/AuthManager.js
- portals/admin/source/src/app/data/Constants.js
Previously, scopes of `apim:api_workflow_view`, `apim:api_workflow_approve`, `apim:admin_settings`, `apim:tenantInfo` or `apim:admin` were mandatory for any user to login to admin portal. With this strict scope requirement, it was hard to maintain access control among admin users. 
With these changes, we have made it configurable. `minScopesToLogin` config in setting.js will be used to evaluate the existing scopes of the admin users at the login. 
With this improvement, we have currently fixed the `Workflow Task` section and configured it with visibility to show only for users with workflow configurations.
Fixes: https://github.com/wso2/product-apim/issues/12618
> Add the support to configure min scopes to login to admin portal via configs

- portals/devportal/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
This PR fixes intl not defined issue when loading keys.
Fixes https://github.com/wso2/api-manager/issues/351
> Fix intl not defined issue when loading keys

- portals/devportal/source/src/app/data/api.jsx
- Fix key generation pages not loading issue
- Related Github Issue: https://github.com/wso2/api-manager/issues/473
- REST API definitions were updated recently with [1]. With this modifications, the tag of `/key-managers` resource has been modified. The UI uses these tags to invoke the REST APIs. The key generation pages were not loading since it was invoking the `/key-managers` resource and the change made to the tag field of the resource was not incorporated to the UI.
- This PR incorporates these REST API definition changes to use the correct tags when invoking the REST APIs from the UI. 
[1] https://github.com/wso2/carbon-apimgt/pull/11282
> Fix Key Generation Pages Not Loading Issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Breadcrumb.jsx
Related to : https://github.com/wso2/product-apim/issues/12489
> Make API name more prominent in developer portal tabs

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
Subscription plans in Websocket APIs prior to APIM-4.0.0 are not visible after migration to a later version. These changes fixes this issue by making the original subscription policies visible after migration.
Fix for - https://github.com/wso2/api-manager/issues/165
Original (pre-migration) subscription policies for async APIs will be visible after the Async Policies with a note.
These original policies will be visible until they are deselected and will not be available for selecting after deselecting.
> Async subscription policies not visible after migration fix 

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
> Fix https://github.com/wso2/api-manager/issues/208
> Update GraphiQL UI to work with graphql-transport-ws protocol

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
This update contains the fix for the issue https://github.com/wso2/product-apim/issues/12836.
The fix was made to stop appearing 'Edit' button and 'Import Definition' button with the refreshing of the API Definition page of an API Product.
> Fix Appearing Extra Buttons when refreshing the API Definition page of an API Product

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/TableView/TableView.jsx
- The pagination choice (items per page) is not persisted in the Publisher portal API listing page. 
- Public Issue:  wso2/api-manager/issues/798
> Fix pagination persistency of Publisher portal

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/WebSubConfiguration.jsx
- Add **enableSubscriberVerification** to enable/disable WebSub subcriber intent verification.
Fix https://github.com/wso2/api-manager/issues/775
> Related PRs: https://github.com/wso2/carbon-apimgt/pull/11572, https://github.com/wso2/product-apim/pull/12989
> Add enableSubscriberVerification property for WebSub APIs

- portals/publisher/src/main/webapp/services/login/idp.jsp
- Use correct URL to retrieve service catalog scopes
- Previously, the publisher settings URL was mistakenly used in-place of the service catalog settings URL. Hence, the scopes retrieved from the publisher settings REST API was appended twice.
- Fixes https://github.com/wso2/api-manager/issues/825
- Used the correct service catalog settings REST API URL to fetch the service catalog scopes
> Use correct URL to Retrieve Service Catalog Scopes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Policies.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/GeneralDetails.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyCreateForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/PolicyViewForm.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/Types.d.ts
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/Types.d.ts
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
This PR adds the UI support for policies feature to select and use different API types.
API Types are HTTP, SOAP and SOAPTOREST.
Fixes : https://github.com/wso2/product-apim/issues/12559
UI improvements.
1. Policy list at API level will be filtered based on the API type.
2. Gateway selection for policies tab will be enabled only for HTTP policies.
3. Policies create and view form will have a section to select/view supported API type.
> Add the policies support for SOAP and SOAP to REST API types

- portals/publisher/src/main/webapp/site/public/conf/settings.json
- Add ".yaml" extension to the supported document types.
- Fixes https://github.com/wso2/api-manager/issues/895
> Add yaml file extension to supported doc types

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- tests/cypress/integration/admin/09-add-km.spec.js
To fix the NPE error when adding WSO2-IS as Key Manager from the Admin portal.
Fixes: https://github.com/wso2/api-manager/issues/885
- UI validation added for other required fields: userInfoEndpoint and scopeManagementEndpoint
- Validation added to validate before searching a value for revokeOneTimeTokenEndpoint since this is only for resident KM.
Related PR: https://github.com/wso2/carbon-apimgt/pull/11626
> Fix error adding WSO2-IS as Key Manager from Admin portal

- portals/publisher/src/main/webapp/openapitools.json
- portals/publisher/src/main/webapp/source/Tests/Utils/setupUtils.ts
The download issue of the definition is fixed with this PR. Still some unit tests are failing. We need to look in to those.
Fixes : https://github.com/wso2/api-manager/issues/1015
> Fixing OAS definition download issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
> Fix https://github.com/wso2/api-manager/issues/1056
> Pass endpoint_security from initial state when updating endpoint_type.
> Pass existing security_endpoints when setting endpoint_type

- portals/publisher/src/main/webapp/source/src/app/data/api.js
- Fix the issue occurring when updating the Definition of an API
- Fixes https://github.com/wso2/api-manager/issues/921
- Add requestBody to validateOpenAPIDefinition REST API call during API Definition Update Scenario similar to [1] and [2]
[1] https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/data/api.js#L152-L165
[2] https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/data/api.js#L175-L188
> Fix the issue occurring when updating the Definition of an API

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/AsyncApiConsole/AsyncApiUI.jsx
In the try-out console of the DevPortal, it passed the hub parameters as query parameters in the POST request. With this improvement, a curl will be generated which will pass the hub parameters in the request body as form-data and the POST request content type is 'application/x-www-form-urlencoded'.
Resolves: https://github.com/wso2/api-manager/issues/871
> [Improvement] Try-Out console of WebSub API sending form-url-encoded type request

- portals/publisher/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/source/src/app/data/api.js
- Previously, there was an issue where configuration not loaded dynamically from settings.json. It was fixed by @chanaka3d.
- Therefore now custom configuration can be added wherever necessary when fetching APIs.
- Fixed https://github.com/wso2/api-manager/issues/731
- Fixed https://github.com/wso2/api-manager/issues/1322
- Fixed https://github.com/wso2/api-manager/issues/756
- Added configurations parameters in settings.json to load and used in APIs call.
- Default configuration value was fixed to `80`.
> Add dynamic configuration loading

- portals/publisher/src/main/webapp/webpack.config.js
Fix for issue https://github.com/wso2/api-manager/issues/189
> Adding javascript syntax highlighting to mock service code editors

- portals/admin/src/main/webapp/source/src/app/components/APICategories/AddEditAPICategory.jsx
- API category edit option causes an error in the admin portal for migrated API categories with no description.
- Fixed https://github.com/wso2/api-manager/issues/1340
- Added additional null check when validating description in api-categories
> Add additional null check when validating description in api-categories

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
As $Subject this will add version at the end of the URL only if {version} is not there in the context.
- https://github.com/wso2/api-manager/issues/724
> Resolve version in correct way in publisher tryout console

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
To fix enabling "Requires re-subscription when publishing the API" is not working.
Fixes: https://github.com/wso2/api-manager/issues/1307
> Fix enabling "Requires re-subscription when publishing the API" not working

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- Resolves https://github.com/wso2/api-manager/issues/1537
This PR fixes the issue where API creation is not properly validating whether the context that is being used is already available when it comes to dynamic contexts.
> Fix duplicate context allowed issue when a templated context is used

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
With this fix, it allowed having a documentation name with spaces when adding documents to an API.
Fixes: https://github.com/wso2/api-manager/issues/1560
> Allowing to have a documentation name with spaces when adding documents for an API

- tests/cypress/integration/publisher/012-documents/00-add-edit-inline-document.spec.js
With this fix, it allowed having spaces in the name of documentation added under an API.
Resolves: https://github.com/wso2/api-manager/issues/1560
> [UI Test] Added test to check creating document with name having spaces

- portals/publisher/src/main/webapp/source/src/app/data/APIProduct.js
- Handle error scenario when uploading product thumbnails
- Related Issue: https://github.com/wso2/api-manager/issues/1280
- When calling the product thumbnail upload API, if an error occurs, the error gets caught within the method but does not propagate the error to the caller. Hence, it does not get captured in the catch block of the caller. This PR sends the error to the caller so that it gets captured in the catch block of the caller
https://github.com/wso2/carbon-apimgt/pull/11872
> Handle Error Scenario When Uploading Product Thumbnails

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Listing.jsx
Fixes https://github.com/wso2/api-manager/issues/1608
> Fix Navigates to a Not found page when click on document of an API product

- portals/devportal/src/main/webapp/services/logout/logout_callback.jsp
- portals/publisher/src/main/webapp/services/logout/logout_callback.jsp
- Removed session state token related to publisher and devportal once user logged out from respective portal
- Related to https://github.com/wso2/api-manager/issues/1648
- Add empty string for the cookie value once user logged out from portals
> Remove devportal and publisher session state cookie after user logout

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- Fix https://github.com/wso2/api-manager/issues/1844
- ForwardPort https://github.com/wso2-support/apim-apps/pull/117
- Gateway Access URL should displays the host name which given for `ws_endpoint` in the `deployment.toml` file. However in the publisher and dev-portal it showed the host name given for `http_endpoint`.
> Add WebSocket Host to Gateway Access URL in portals 

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/KeyManagerConfiguration.jsx
- This PR will introduce the checkbox type to the Key Manager configurations.  
- Related Issue: https://github.com/wso2/api-manager/issues/1821
- A new property has been introduced to the WSO2-IS Key Manager configurations with the checkbox type. 
- The UI will be displayed as follows.
- The behaviour will be as follows.
- When adding a WSO2-IS key manager, if the checkbox was not clicked, the following object will be sent to the backend
- When adding a WSO2-IS key manager, if the checkbox was clicked, the following object will be sent to the backend
- When adding a WSO2-IS key manager, if the checkbox was clicked and un-clicked, the following object will be sent to the backend
> Introduce Checkbox Type to Key Manager Configurations

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.test.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Properties/Properties.jsx
- This PR resolves the master fix for wso2-enterprise/wso2-apim-internal#3166.
This PR adds the UI implementation of mandatory custom properties support feature to the publisher portal. This feature can be enabled by defining server config or tenant config as below.
Server Config
```
[[apim.publisher.custom_properties]]
required=true
name="PropertyName"
description="Property Description"
```
Tenant Config
Add the configuration as shown below by navigating to the Settings -> Advanced page of the admin portal
```
"PropertyConfigurations": {
"Properties": [
{
"Name": "PropertyName",
"Required": true,
"Description": "Property Description"
}
]
}
```
UI will change as follows if the config is defined:
This PR includes a rest API validation to the mandatory custom properties when updating the …
> [RRT] Add UI implementation for mandatory custom properties support feature

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Implemented an information icon to show the product revision description only when a description is added.
Implemented a Returnbox to view the description. The Ui will be as follows.
Resolves : https://github.com/wso2/api-manager/issues/1905
> Add information icon to show product revision description.

- tests/cypress/integration/admin/09-add-edit-delete-km.spec.js
- tests/cypress/support/commands.js
Fix https://github.com/wso2/api-manager/issues/1951
> Add UI tests for editing claim mappings under Token Handling Options in Advanced Configurations

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
- Resolves https://github.com/wso2/api-manager/issues/1986
This PR wii add the implementation of hiding the "Get Test Key" button when token hashing is enabled using the following config in  deployment.toml
```toml
[apim.oauth_config]
enable_token_hashing = true
```
> Hide "Get Test Key" button when token hashing is enabled

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- Fixed issue where any user can delete the publisher access roles from UI of api configuration page.
- This is anyway blocked from the backend.
- Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/3409.
- Made disable option true based on the permissions of the user in mui chip widget.
> Add chip disability based on scopes

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/AWSLambdaSettings.jsx
Related git issue : https://github.com/wso2/api-manager/issues/1878
Related PRs : https://github.com/wso2/carbon-apimgt/pull/12031
- In lamba, content can be sent as either encoded or not, this is goverened by the new checkbox introduced in AWS lambda Settings UI section.
> Add UI changes to enable content encoding in lambda

- .github/workflows/ui-test.yml
This PR fixes the PR build failures in this repo by downgrading the java version to **11.0.19+7** & changing the distribution to **temurin**.
> Downgrade java version & change distribution to fix PR build failures

- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/AdminTable/AdminTableBody.jsx
- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/Commons/AddRoleWizard.jsx
- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/Commons/SelectPermissionsStep.jsx
- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/ListRoles.jsx
- tests/cypress/integration/admin/07-add-scope-mapping.spec.js
This PR adds the new feature of mapping multiple internal roles for a custom role & enhances warn messages when having UI error on Scope-Role mapping UI on the admin portal. Sample UIs are as follows.
**Warn Message when the textbox is empty**
**Warn Message when having an UI error**
**When selecting multiple roles with this feature UI will be as follows**
**This is how it looks in the table after mapping roles**
[4.1.0] - https://github.com/wso2-support/apim-apps/pull/158
[4.2.0] - https://github.com/wso2-support/apim-apps/pull/159
> Support multiple internal roles mapping feature

- tests/cypress/integration/devportal/000-general/04-change-password-of-a-user.spec.js
- tests/cypress/integration/publisher/001-api-create/07-create-and-publish-api-from-scratch.spec.js
- tests/cypress/integration/publisher/002-api-resources/00-api-resource-create.spec.js
- tests/cypress/integration/publisher/002-api-resources/02-add-assign-global-scopes-for-api.spec.js
- tests/cypress/integration/publisher/005-design-config/03-add-tags-for-the-api.spec.js
- tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
- tests/cypress/integration/publisher/014-comments/01-add-nested-comments-to-api.spec.js
Following test cases are added to the test suite
04-depricate-old-versions.spec.js
02-add-assign-global-scopes-for-api.spec.js
03-add-tags-for-the-api.spec.js
01-add-nested-comments-to-api.spec.js
> [Main] Adding new test cases for API Publisher

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GraphQLConsole/GraphQLUI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/ApiKeyHeader.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
Resolves https://github.com/wso2/api-manager/issues/1672
1. Support for setting a custom value for API key header in Runtime config ( For REST, GraphQL APIs and APIProducts )
2. Necessary support for custom API key header in dev portal test consoles ( API and GraphQL consoles )
https://github.com/wso2/apim-apps/pull/463
> Frontend changes for custom api key header feature

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APISecurityAudit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/GoToDefinitionLink.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/leftMenu/DevelopSectionMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
Issue #2274: Throwing the 500 response when refreshing the API definition page and Business info section in the Publisher - APIM 4.2.0
Issue #2273: Previous validation errors are showing for valid API definition - APIM 4.2.0 publisher
Issue #2274: 
When refreshing pages with space included urls, urlmalformed error is thrown as below.
```
ERROR - AuthenticationValve Error while normalizing the request URI to process the authentication: 
java.net.URISyntaxException: Illegal character in path at index 61: /publisher/apis/950a0b1a-91b4-404d-8f8b-bbdd144bb1e8/business info
at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
at java.net.URI$Parser.checkChars(URI.java:3084) ~[?:?]
at java.net.URI$Parser.parseHierarchical(URI.java:3166) ~[?:?]
at java.net.URI$Parser.parse(URI.java:3125) ~[?:?]
at …
```
> Changes spaces to hyphens in space included urls and Sets validation errors to empty array when url is valid

- portals/publisher/src/main/webapp/site/public/conf/settings.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
This PR fixes https://github.com/wso2/api-manager/issues/2289. In this PR we have introduced a configurable maximum subscription limit and removed the custom footer that was initially added for manual pagination purposes.
> Introduce configurable maximum subscription limit

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/Transports.jsx
- Fix https://github.com/wso2/api-manager/issues/2202
- According to the expected behaviour of the APIM if a user enable Mutual SSL in transport level security for an API, they could not use HTTP for that API. However in the publisher portal UI, users were able to select http even though Mutual SSL is enabled.
- In this PR HTTP checkbox will be unchecked and disabled if an user decided to enable Mutual SSL.
> Uncheck and disable http checkbox when Mutual SSL is enabled

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/Linting/Linting.tsx
Fixing : https://github.com/wso2/api-manager/issues/2335
Add `"schema": spectralFunc.schema` to `spectralFunctions` in linter.
> Add spectralFunc.schema config to swagger linter

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx
The users can create an API-only MTLS, but the user can't publish it through the Lifecycle tab. User can publish the API through the Overview page only.  
Added an additional condition to check the isMutualSslOnly status.
Related Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4586
Fix is taken from:
https://github.com/wso2-support/apim-apps/blob/support-9.0.432.x-full/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx#L375
> Fixed publish button is disabled when only mutual ssl is enabled

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionPoliciesManage.jsx
When the subscription policies count is higher than 25, the admin portal shows the entire policies (example 40 policies) but publisher portal limit it to 25. 
Added a new config property as `subscriptionPolicyLimit` to the settings.js.
Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4446
Related PR: https://github.com/wso2-support/carbon-apimgt/pull/6163
If the user wants to change the maximum number of subscription policies to be displayed in the publisher portal,  User can add `subscriptionPolicyLimit` property in the `repository/deployment/server/jaggeryapps/publisher/site/public/conf/settings.js` file.
Ex- subscriptionPolicyLimit: 80
> Fixing Limited view of subscription policies in Publisher portal issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
> Subscriptions in the publisher menu can be filtered by subscriber names through an MUIDataTable. When there is a large number of subscriptions in the same page, there needs to be an option of filtering by a textbox filtertype.
> https://github.com/wso2/api-manager/issues/2249
> Filtering subscriptions based on subscriber by textbox filtertype

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/SubscriptionPolicySelect.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/SubscriptionTableData.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/SubscribeToApi.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/Tokens.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APICategories.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/OperationGovernance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/asyncapi/OperationGovernance.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/SubscriptionsTable.jsx
Fixing : https://github.com/wso2/api-manager/issues/2354
> Add searchable option to overpopulated list dropdowns

- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Listing/Listing.tsx
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Policies/GlobalSpecificComponents/Policies.tsx
- tests/cypress/integration/publisher/022-gateway-policies/00-gateway-policy.spec.js
To enhance the quality and reliability of the Gateway Policy feature by introducing UI tests. These UI tests are designed to validate the functionality, user interactions, and edge cases within the Gateway Policy feature's user interface
Test the UI implementations related to: https://github.com/wso2/api-manager/issues/1710
> Add cypress tests for Gateway-Policy feature UI

- portals/publisher/src/main/java/org/wso2/carbon/apimgt/ui/publisher/Util.java
- portals/publisher/src/main/webapp/services/login/introspect.jsp
- Domain name (@carbon.super) of logged in username cannot be omitted in the Publisher Portal when there is an external IDP.
- Fixes https://github.com/wso2/api-manager/issues/2308.
- Added `isEnableEmailUserName = Util.isEnableEmailUserName();` method to utils.js to fetch whether the email user name is enabled or not
- Based on that, `@carbon.super` part is removed with the introspect call.
> Remove domain(@carbon.super) of logged-in username when there is an external IDP

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/AttachedPolicyCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/AttachedPolicyList.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PoliciesExpansion.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyDropzone.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/components/FlowArrow.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/components/TabPanel.tsx
> Reuse shared components in API Policies

- pom.xml
This PR will exclude following dependencies from admin, publisher and devportal webapp lib folders.
- pax-logging-log4j2-1.11.10.jar
- pax-logging-api-1.11.10.jar    
- osgi.cmpn-6.0.0.jar        
- osgi.core-6.0.0.jar
> Exclude paxlogging dependencies from the webapp libs

- portals/publisher/src/main/webapp/source/src/app/data/APIProduct.js
- Resolves https://github.com/wso2/api-manager/issues/2430
- Change API product version to correct value from default API product version.
> Fix an API product download issue

- portals/admin/src/main/webapp/site/public/locales/en.json
- portals/admin/src/main/webapp/site/public/locales/fr.json
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/ListGWEnviornments.jsx
- portals/admin/src/main/webapp/source/src/app/data/api.js
> Add type feild to gateway UI

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/GlobalPolicies/Listing/Listing.tsx
In current implementation, if a publisher who has privileges only to view Global Policies logged in to the publisher and in that scenario, system does not have any global policies, he will get redirected to the welcome page. Currently welcome page of Global Policies give a button to create a Global Policies. 
Since that user does not has the privileges to create a user, he will not be able to access the button and will get redirected to the not found page. But showing that button is misleading, we have improved the code to give a proper message to show that user cannot create global policies as user does not have the right privileges. We also removed the button.
New Improvement
> Add an improvement to an edge case in Global Policies

- tests/cypress/integration/devportal/002-subscriptions/03-change-subscription-tier-on-an-application.spec.js
- tests/cypress/integration/devportal/003-test/00-tryout-api-invocations-from-swagger-console.spec.js
- tests/cypress/integration/publisher/002-api-resources/02-add-assign-global-scopes-for-api.spec.js
This PR fixes test failures in test files below.
- change-subscription-tier-on-an-application.spec.js
- tryout-api-invocations-from-swagger-console.spec.js
- add-assign-global-scopes-for-api.spec.js
> Fix cypress test failures

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- This PR adds a fix to overcome the loading issue of the Deployments page
- Related Issue: https://github.com/wso2/api-manager/issues/2518
- The getRevision and getDeployedEnv functions use the apiType property of the api object
- These functions are called after the setState function which sets the api object
- But the setState function does not immediately apply this change
- Hence, ensured the getRevision and getDeployedEnv functions are executed after the state has been updated by adding them to the callback of the setState function
> Fix Deployments Page Loading Issue

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
- Implemented useRef to maintain the current values of securityScheme and authorizationHeader, ensuring the latest state is accessed within closures.
Git Issues: https://github.com/wso2/api-manager/issues/2603, https://github.com/wso2/api-manager/issues/2564
> Refactor: Use useRef for dynamic securityScheme and authorizationHeader access

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/TransportLevel.jsx
- This PR fixes the issue https://github.com/wso2/api-manager/issues/2606
- Due to the type of the null, the initialization of mandatoryValue sets incorrectly. This PR fixes the issue.
> Fix null check in TransportLevel

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/ApiKeyHeader.jsx
fixes: https://github.com/wso2/api-manager/issues/2669
> Remove: APIKey Header customization from publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/APISecurity.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/CheckboxLabels.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
With this fix when migrating from 2.6.0 to later versions, for prototype APIs if the lifecycle state is created or published, HTTP/REST Endpoint is selected and it shows production & sandbox endpoints. If the lifecycle state is pre-released it shows the prototype endpoint.
> [Master] Add additional lifeCycleStatus check for prototype APIs

- portals/devportal/src/main/webapp/package-lock.json
- portals/devportal/src/main/webapp/package.json
- portals/devportal/src/main/webapp/site/public/locales/converter/package-lock.json
- portals/devportal/src/main/webapp/site/public/locales/converter/package.json
Current changes has been done
In In apim-apps/portals/devportal/src/main/webapp
- axios to 0.28.0
- sanitize-html to 2.13.0
- openapi-to-postmanv2 to 4.20.0
- @stoplight/elements to 8.1.0
In apim-apps/portals/devportal/src/main/webapp/site/public/locales/converter
- translate to 3.0.0
> 4.3.0 dependency upgrades

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
Related Issue: https://github.com/wso2/api-manager/issues/2493
> Fix API lifecycle labels are not aligned issue when delete disabled

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/site/public/locales/raw.en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/ListParameters.jsx
1. Undefined is printed in the UI become the component only handles errors or strings. Changed the FromattedMessage to string.
2. SwaggerParser fails to resolve the spec when external https refs are available. Changed it to SwaggerClient's resolve.
> Fix https://github.com/wso2/api-manager/issues/2834

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/Endpoints.jsx
Fixes https://github.com/wso2/api-manager/issues/2828
> Fix Can't view APIs via publisher portal due to missing the sandbox in endpoint security

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AdvancedConfig/AdvanceEndpointConfig.jsx
This update will set the `Leave As-Is` option as the default selected value when creating the SOAP API
- Resolves : https://github.com/wso2/api-manager/issues/2867
> Set the `Leave As-Is` option as the default selected value when creating the SOAP API

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/APICreateMenu.jsx
After clicking the Create API button in the Publisher portal, it gets covered by the Dialog.
Overwritten the inherited margin of the Create API Dialog and added a top margin
Resolves https://github.com/wso2/api-manager/issues/2811
> Fix create new API dislocation in publisher

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/CommonListing.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/TagCloudListing.jsx
- portals/devportal/src/main/webapp/source/src/app/data/api.jsx
When the Devportal UI is loaded and the Tags/API categories section is selected, they can only see the 25 Tags which is the default value. With this update, it will show all the added tags in that section.
Fixes: https://github.com/wso2/api-manager/issues/2947
> Fix the issue of not showing all the tags under Tags/API categories in the devportal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
This PR fixes the issue of gateway environment names overflowing with longer text on the deployments page
Fixes https://github.com/wso2/api-manager/issues/1846
> Fix Gateway environment name overflowing with longer text

- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/Onboarding.jsx
- portals/publisher/src/main/webapp/webpack.config.js
Mistakenly display a success toast to the read only users on creation button click in the service catalog page of the Publisher portal.
Display success toast only after getting a success response. Also updated the webpack config file to run the service catalog page on the 8081 port without an issue
Resolves https://github.com/wso2/api-manager/issues/1573
> Fix wrong toast display issue on the sample service catalog creation using a read only user

- portals/admin/src/main/webapp/source/src/app/components/Throttling/Application/Delete.jsx
This PR fixes the build failure from unused variable `intl`.
> Fix build failure from unused variable

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/TextEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/TryOutConsole.jsx
- Authorization header missing in "Try out" page in the Publisher Portal
- Markdown Controls in the Documents Section Disappear in Long Documents
- Related to https://github.com/wso2/api-manager/issues/3005 and https://github.com/wso2/api-manager/issues/3019
- Add component based styling to markdown editor.
- Handle API key  validations with component rendering in TryOutConsole react component.
> Fix issues related to document markdown editor and tryout console in publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
- To fix the bug identified where the add document button in publisher is not working.
- Set forwardRef to true in injectIntl function to allow the ref to be based to the Higher order component.
> Fix add document not working in publisher portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AIAPI/APICreateAIAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/BackendRateLimiting.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/BackendRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/CommonRateLimitingForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/RequestCountRateLimit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AIBackendRateLimiting/RequestCountRateLimitUnit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIValidation.js
> Add BE Rate Limit Request Count Changes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/TryOut/SwaggerUI.jsx
Ensure that the latest internal API key is correctly applied in the Tryout section of the Publisher portal. 
Fixes https://github.com/wso2/api-manager/issues/3104
Used useRef hook to ensure that the latest `accessToken` is fetched and applied in the `requestInterceptor`.
Note: According to the swagger-ui-react documentation, this behavior should happen by default. It was also observed in earlier versions (v3, v4) that the interceptor worked as expected, but it no longer works in v5 (couldn't find out why). The useRef approach ensures the latest token is always applied, fixing the issue.
> Ensure correct internal API key is used in publisher portal try out

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
Users want a method to configure connection timeout parameters for the OAuth token endpoint when using OAuth-protected APIs. The following UI component has been added to facilitate this configuration.
Fix https://github.com/wso2/api-manager/issues/3032
> Added OAuth Token Endpoint Connection Configurations

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
Fixes https://github.com/wso2/api-manager/issues/3123
> Disable the certificate save button when business plan is empty

- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/Overview.jsx
The business plan row in the DevPortal Application Overview wasn’t showing up when the policy description was empty because of the rendering conditions. The reset button was also not showing. The purpose of the PR is to fix that bug.
Fixes https://github.com/wso2/api-manager/issues/3163
Updated the rendering conditions.
> Fix Application Throttle Policy Reset button visibility bug

- portals/admin/src/main/webapp/source/src/app/components/ApplicationSettings/ListApplications.jsx
- Allow applications to be searched by its name in the admin portal in the change application owner page.
- Related to https://github.com/wso2/api-manager/issues/3100
- Add new `searchQuery` variable instead of the existing `owner` variable,  to include both application name and owner.
- Update the UI text to include the new functionality
> Add search by application name support for change application owner page

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/index.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/LeftMenuItem.jsx
Fixing the alignment issues in different styling modes in API Details left menu.
Fixes https://github.com/wso2/api-manager/issues/2751
Updated the 3 left menu styles
https://github.com/user-attachments/assets/51e453a7-a31c-4dd0-833a-e2840a53204d
https://github.com/user-attachments/assets/26b66f17-5008-4e61-9a13-c8f2144cbf59
https://github.com/user-attachments/assets/013668e6-5ace-4d61-a949-aa127c7d19f9
> Fix alignment issues in API Details left menu

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
Fixes: https://github.com/wso2/api-manager/issues/3191
> Fix green check mark for AI API  without backend security

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/AppConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AccessControl.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Create/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/ChipInput.js
To fix the alignment issues in ChipInput components
Fixes https://github.com/wso2/api-manager/issues/3224
**Note:**
I noticed that we are using the [mui-chips-input](https://viclafouch.github.io/mui-chips-input/) library in the admin portal, but a custom component in the other two portals. Maybe we can replace the components in the publisher and dev portals with the same library used in the admin portal (if there's no specific reason for using the custom component).
> Fix alignment issues in ChipInput components

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
Add a toggle button to hide and un-hide the API Key value. Once the key is saved it will stay hidden.
Fix: https://github.com/wso2/api-manager/issues/3193
> Fix ApiKey visibility

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/UploadCertificate.jsx
Fixes https://github.com/wso2/api-manager/issues/3123
From the publisher portal's API configurations we can add a certificate for Mutual SSL in Transport Level Security. Users should not be allowed to add certificates if a business plan is not selected. But if a user first selects a business plan, closes the certificate upload window and add a certificate again without a business plan, the save button is enabled.
The`isPoliciesEmpty` state is reset to `true` when the certificate upload window is closed.
The certificate upload flows of endpoint security and mutual SSL have been tested.
> Reset isPolicyEmpty flag when certificate upload window is closed.

- portals/admin/src/main/webapp/source/src/app/components/Base/NavigatorChildren.jsx
Added functionality to hide the 'Usage report' in the navigation bar when the transaction counter is disabled.
Resolves: https://github.com/wso2/api-manager/issues/3122
> Transaction Counter UI Improvements

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProduct.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/navbar/GlobalNavLinks.jsx
> Make all navigation bar links visible to all users, as anyone who can log in to the publisher portal can view every page.
> Fix `FormattedMessage` usage for correct string passing.
> Related Issue: https://github.com/wso2/api-manager/issues/3118
> Remove user role checks from navigation bar. 
> Replaced the direct usage of `FormattedMessage` with `intl.formatMessage`.
> Make all navigation bar links visible to all users

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/MaxBackendTps.jsx
Display the backend throughput config as unlimited when maxTps value is undefined
Fixes https://github.com/wso2/api-manager/issues/3198
> Fix the default value of backend throughput options

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/SwaggerUI.jsx
Ignore empty auth headers in DevPortal Tryout in third party APIs. 
Fixes https://github.com/wso2/api-manager/issues/3181
> Ignore empty auth headers in DevPortal Tryout in third party APIs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GenericEndpointAdd.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/LoadbalanceFailoverConfig.jsx
- Resolves: https://github.com/wso2/api-manager/issues/3274
> Fix Endpoints UI crash issue when configuring load balanced/failover endpoints

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewVersion/NewVersion.jsx
> In publisher portal, clicking the "Create" button in the "Create New Version" page more than once during the process leads to duplicate entries. 
Related to - https://github.com/wso2/api-manager/issues/3256
> To disable the "Create" button during the API version creation process,  a new  state `isLoading` is introduced to the `CreateNewVersion` component. Initially, `isLoading` is set to false. When the `handleSubmit` method is triggered, `isLoading` is set to true, which disables the "Create" button, preventing multiple submissions. After the API request completes, whether successfully or with an error, `isLoading` is reset to false, re-enabling the button.
> Disable create new version button while handling submit

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/AIEndpointAuth.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
This PR fixes the following UI issues:
- Consider an AI API which has a valid API Key associated to it. When deleting the available API Key either from production or sandbox, the `Save` button remains active. This PR fixes this issue by disabling the Save button when no API Key is provided
- If a valid API Key was already added for the AI API, when trying to type something into the existing text field, the typed in values are appended to the `*` characters that are masking the available key. This was fixed so that if one wishes to edit the existing key, previously save value is discarded.
> Bug fixes related to AI API Endpoint page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/UploadPolicyDropzone.tsx
- Currently, any type of file can be uploaded on a policy creation. Need to restrict the file types to `.j2` and `.xml`
Fixes: https://github.com/wso2/api-manager/issues/2663
> Add: Validation for Policy Upload

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
Fixing the alignment of "Read Only" button in the top menu.
Fixes https://github.com/wso2/api-manager/issues/3299
> Fix alignment of read only label in top menu

- portals/devportal/src/main/webapp/source/src/app/components/Applications/ApplicationFormHandler.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/InfoBar.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Listing/AppsTableContent.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/AppConfiguration.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ImportExternalApp.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/KeyConfiguration.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyForm/UploadPolicyDropzone.tsx
This UI fix introduces a capability that could represent a valid business requirement for certain customers. Consequently, the API-M product will include a system property that enables update access for users within the application-sharing group. This feature will be disabled by default to ensure the current behavior remains unchanged.
Fixes: https://github.com/wso2/api-manager/issues/3446
Introduced `orgWideAppUpdateEnabled` system property to enable this capability.
Ex.: `sh api-manager.sh -DorgWideAppUpdateEnabled=true`
Related PR: https://github.com/wso2/carbon-apimgt/pull/12731
> Add support for org-wide application update

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Monetization/BusinessPlans.jsx
The error message "Something went wrong while configuring monetization" was improperly thrown when disabling/enabling monetization for an API due to the businessPlans object being undefined.
Prevented the businessPlans ref from being overridden using `forwardRef: true`.
Fixes [wso2/api-manager#3497](https://github.com/wso2/api-manager/issues/3497)
> Fix improper error notification thrown when monetizing APIs

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/ListKeyManagers.jsx
- This fix resolves the issue of an unexpected behaviour when enabling/disabling key managers in admin portal where it needs multiple clicks and a page refresh to successfully enable/disable a key manager.
- In the UI implementation, the Alert component from material UI had being incorrectly used. It does not have a success function which gives an error.
- Replaced the MUI Alert component with the Alert in the shared components.
Fixes https://github.com/wso2/api-manager/issues/3308
> Fix UI bug related to enable/disable key manager in admin portal

- portals/admin/src/main/webapp/site/public/locales/en.json
- portals/admin/src/main/webapp/site/public/locales/fr.json
- portals/admin/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/devportal/src/main/webapp/site/public/locales/en.json
- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Base/Footer/Footer.jsx
- tests/cypress/integration/e2e/externalDevPortals/00-enable-external-dev.spec.js
- tests/cypress/integration/publisher/000-general/00-deploy-sample-api.spec.js
- tests/cypress/support/commands.js
- Update APIM version in portal footer to APIM 4.5.0
> Update APIM Version in Portal Footer

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
This fix disables the Deploy button in the deployments tab for a read only user (observer role), when the API is not initially deployed.
Restricted the initial Deploy button only for the roles creater and publisher.
Fixes https://github.com/wso2/api-manager/issues/2362
> Fix UI bug related to disabling Deploy button for observers

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
**Purpose**
- This pull request fixes the issue where the "Generate Keys" button of other key managers gets disabled when keys are provided for a third-party key manager. 
- Resolves: https://github.com/wso2/api-manager/issues/1854
**Approach**
The value of the mode variable is updated on every tab change. Based on the current value of the mode variable, the "Generate Keys" button is enabled or disabled accordingly.
> Fix: "Generate Keys" Button Disables Incorrectly for Third-Party Key Managers (#1854)

- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/Commons/ListAddOns.jsx
- portals/admin/src/main/webapp/source/src/app/components/RolePermissions/ListRoles.jsx
* This pull request addresses the issue where the "Reload" button in the Admin Portal Scope Assignments page does not function as expected, failing to reset the data and search input to their original states.
* Resolves: https://github.com/wso2/api-manager/issues/1329
* To ensure that the "Reload" button in the Admin scopes page restores the original data and clears the search input when clicked.
- Introduced a new state variable `searchText` to keep track of the search input value.
- Created a `fetchData` function to centralize data fetching logic and reset the search input.
- Updated the `useEffect` hook to use the `fetchData` function.
- Modified the `onSearch` function to update the `searchText` state.
- Updated the `ListAddOns` component to accept a `searchValue` prop and set it as …
> Fix: "Reload" Button in Admin Scopes Not Functioning Correctly (#1329)

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/ApiCreateGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/GraphQL/Steps/ProvideGraphQL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/ImportDefinition.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/GraphqlAPIMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
This feature enhances the GraphQL API creation capabilities by adding support for additional methods: creating APIs using an SDL URL and using the introspection method by providing an endpoint.
- Added new radio buttons for GraphQL API creation using SDL URL and endpoint (for introspection).
- Made the endpoint input in the API creation UI readonly when creating a GraphQL API using an endpoint.
- Added new API call functions for validateGraphQLSchema using SDL URL and endpoint.
- Updated existing UI texts to reflect the new functionality.
Related to issue: https://github.com/wso2/api-manager/issues/3444
> Add graphql api creation by SDL url and introspection

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/SharedOrganizations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/StoreVisibility.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/OrganizationSubscriptionPoliciesManage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
-  Initial solution for: https://github.com/wso2/api-manager/issues/3531
- This PR provides initial publisher portal UI for:
- Add/edit shared organizations in the `Basic Info` page of an API
- Add/edit business plans for shared organizations in the `Subscriptions` page of an API
- Todo:
- Add radio buttons for shared organizations selection (All, None, Selected Organizations)
- Add current organization subscriptions and shared organization subscriptions in a single table
> Add Publisher Portal Changes for Organization Feature

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/CreateEditForm.jsx
Resolves: https://github.com/wso2/api-manager/issues/126
On the edit metadata page of a document in the publisher portal, when the document type is changed from `How To` to `Other,` the save button is still enabled even `Other Document Type` mandatory field is empty.
Before the fix, it only checks for empty string and not for NULL values. Fixed to validate `NULL` values
> fix: condition check if the sourceUrl and otherTypeName is NULL

- portals/devportal/src/main/webapp/services/login/login_callback.jsp
- portals/devportal/src/main/webapp/services/logout/logout_callback.jsp
Can't fully capitalize the cookie name ORGANIZATION_Default because '_Default' part is being set internally when retrieving the cookie.
> Fix orgname being null in devportal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/SharedOrganizations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/OrganizationSubscriptionPoliciesManage.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/Subscriptions.jsx
- Related Issues: https://github.com/wso2/api-manager/issues/3531
- Add radio buttons to select options to share API with organizations
- Check whether organization access control is enabled or not to show organization based subscription policies in Subscriptions page and Shared organizations in Basic Info page
- Fix styling issues in Subscriptions page
> [Publisher] Add multiple changes related to organization feature

- portals/admin/src/main/webapp/source/src/app/components/Base/RouteMenuMapping.jsx
- portals/admin/src/main/webapp/source/src/app/components/Labels/AddEditLabel.jsx
- portals/admin/src/main/webapp/source/src/app/components/Labels/DeleteLabel.jsx
- portals/admin/src/main/webapp/source/src/app/components/Labels/ListLabelUsages.jsx
- portals/admin/src/main/webapp/source/src/app/components/Labels/ListLabels.jsx
- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APICategories.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
- Resolves https://github.com/wso2/api-manager/issues/3503
This PR introduces the UI implementation for the Labels Feature, complementing the backend functionality. The key aspects of this implementation include:
- Label Management UI:
- Create, update, delete, and retrieve labels through intuitive interfaces.
- View label usage details for better resource management.
- Associate and manage labels with APIs in the publisher.
- Extensibility:
- The UI has been designed to support future expansions, enabling label management for applications and other resource types.
> [4.5.0][FEATURE] Implement Labels Feature - UI Enhancements

- portals/admin/src/main/webapp/site/public/locales/en.json
- portals/admin/src/main/webapp/site/public/locales/fr.json
- portals/admin/src/main/webapp/source/src/app/components/Base/Navigator.jsx
- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
- portals/admin/src/main/webapp/source/src/app/components/Organizations/AddEditOrganization.jsx
- portals/admin/src/main/webapp/source/src/app/components/Organizations/ListOrganizations.jsx
- portals/admin/src/main/webapp/source/src/app/data/Constants.js
- portals/admin/src/main/webapp/source/src/app/data/api.js
- portals/devportal/src/main/webapp/services/login/login_callback.jsp
- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/devportal/src/main/webapp/source/src/app/data/api.jsx
Updated the UI with 3 radio buttons None, All and Select to assign organizations to a specific key manager.
For al already existing key manager or a newly added key manager, 'All' will be set by default, if not updated.
When selected,
- ALL, an array including the keywork 'ALL' 
- NONE, an array including the keywork 'NONE'
- SELECT, an array with the UUIDs of selected orgs
will be passed in allowedOrganizations for the specific keymanager.
At the rest API level, these will be handled appropriately by assigning user's current organization if NONE, allowing any organization if ALL, and allowing only selected orgs if SELECT.
For already exisitng Key Managers, allowedOrganizations will be an empty list, which will also be handled from the rest API level.
> Radio button selection to assign orgs for a Key Manager in admin portal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/ShareAPI/ShareAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
- Add validations to check whether the logged in user has an organization and organizations are available in the environment
> [Publisher] Add validations to organization feature

- portals/devportal/src/main/webapp/services/logout/logout_callback.jsp
This PR fixes an issue where logging out from devportal when the home page has been enabled redirects the user to /apis instead of /home.
Check whether the home page has been enabled and redirect the post logout flow accordingly.
Fixes: https://github.com/wso2/api-manager/issues/3567
> Fix logout redirection issue when home page is enabled

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/DesignConfigurations.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfigurationWebSocket.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/APIRateLimiting.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
Fixed an issue with the gatewayType of the api object for the ApiProducts
> API Product Bug Fixing for the Gateway Types

- .github/workflows/ui-test.yml
- Bump upload-artifact version
> Bump upload-artifact Version

- portals/devportal/src/main/webapp/services/login/introspect.jsp
- When user authentication token is revoking if the username is not defined a TypeError thrown
- This change will handle this error when user authentication token is revoking with undefined username
- Related issue - https://github.com/wso2-enterprise/wso2-iam-internal/issues/2436
- Related PR - https://github.com/wso2/carbon-identity-framework/pull/6495
- warning is logged when username is not defined.
> Handling undefined username in the introspect response.

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- portals/publisher/src/main/webapp/source/src/app/data/APIProduct.js
- Remove visibleOrganizations field when updating API Products
- Modify the following gateway names
- `Regular Gateway` -> `Universal Gateway`
- `APK Gateway` -> `Kubernetes Gateway`
- Fixes: https://github.com/wso2/api-manager/issues/3665
> Remove visibleOrganizations field when updating API Products

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Scopes/EditScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/Create/CreateScope.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Scopes/EditScope.jsx
Improve the UX of role addition from secondary user store while creating/editing scopes. The fix programmatically converts the domain name in the role to upper case in order to be consistent with other instances in API Manger/
> Improve UX of role addition.

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ApplicationCreateForm.jsx
Hide the 'Share with the Organization' button in Application creation form for users who dont belong to an organization.
The logged-in user's organization name is stored in the sessionStorage at user login. Retrieve this item and hide the button if it is null.
Fix: https://github.com/wso2/api-manager/issues/3676
> Hide Share with Organization button for non-org scenarios

- portals/admin/src/main/webapp/source/src/app/components/AdminPages/Addons/ListBase.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
This PR,
- Disables update option for readOnly gateway environments
- Updates gateway type display names to align with new naming convention.
- Fixes https://github.com/wso2/api-manager/issues/3726 by disabling multi vhost support for AWS gateways.
> Fixes multiple issues in Gateway Environments UI

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/Menus/DesignAssistantMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/components/LandingMenu.jsx
> Fix publisher landing page UI

- pom.xml
- portals/admin/pom.xml
- portals/devportal/pom.xml
- portals/pom.xml
- portals/publisher/pom.xml
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/APICreateWithAI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/components/DisplayCode.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/components/LoadingDots.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/components/SampleQueryCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/components/SimilaritySearch.js
> This PR includes several changes to the UI of API Design Assistant.
> Related issue: https://github.com/wso2/api-manager/issues/3564
> 1. Removes the API type from the sample query cards, rearranges the order and placing and adds a new card for GraphQL APIs.
> 2. Aligns the loading dots with the 'Generating a response' text and also shifts this component a little bit to the right.
> 3. Adds a download button for all API types next to the 'View Source' toggle (for REST APIs) to enable downloading the source code of the API specification.
> Below is an image of how it is shown for REST APIs.
> Below is an image of how it is shown for GraphQL or Async APIs.
> Below is an image of it having the functionality to download the spec to their 'Downloads' folder.
> 4. Adds functionality to …
> [API Design Assistant] Add UI fixes to individual components

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/StreamingAPI/APICreateStreamingAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/SampleAPI/components/TaskState.jsx
$subject
- Update the error handling logic in deployment page in governance blocking scenarios to prevent resetting the deployment page in governance blocking scenarios [1]
- Improved the error handling of Create & Publish operations in Publisher [2]
- Handled the errors in async API creation/publish
- Added the download violations button to the error alert
[1] 
https://github.com/user-attachments/assets/ec9b3c81-9cef-4395-9b00-beb92e1df69e
[2] 
https://github.com/user-attachments/assets/3a724c65-49e1-4f67-b0ba-a8ae2ba8c487
> Improve error handling in governance blocking scenarios

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
Purpose of the PR is to fix https://github.com/wso2/api-manager/issues/3661
When the user clicks the security configuration button while the endpoint text box is focused, both [editEndpoint](https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx#L439) and [toggleEndpointSecurityConfig](https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx#L656) are triggered simultaneously. This causes the [securityInfo](https://github.com/wso2/apim-apps/blob/2534c2404beb9d59c742c77719da3554cd00fc1f/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx#L365) to become …
> Ensure security config dialog is properly updated with props changes

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/Landing/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/TopMenu.jsx
Resolves: https://github.com/wso2/api-manager/issues/3753
With this fix the 'Create API with AI' button in the top menu also will be disabled when AI features are disabled.
> Removed the 'Create API with AI' card in the landing page when AI features are disabled 

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Subscription/SubscriptionUpdate/SubscriptionUpdate.jsx
The final UI will be as follows,
- Add the "Approve" text.
- Add the arrow icon for Tier transition
Resolves:https://github.com/wso2/api-manager/issues/3732
> Fix the issue of "Approve" Text not Visible in Publisher Portal Subscription Update Tasks List

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelCard.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelFailover.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelRoundRobin.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/ModelWeightedRoundRobin.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/CustomPolicies/Types.d.ts
With this PR, we improve the AI API policy parameter value to include the endpoint name. This is done to address the AI API import improvements reported via [1].
- Before:
```json
{
"production":[
{
"model":"mistral-medium",
"endpointId":"e910d0e5-d4d4-4a22-85dc-7e9e9228c721--PRODUCTION",
"weight":100
}
],
"sandbox":[
{
"model":"mistral-small-latest",
"endpointId":"d2b3c0e7-0a7f-4e63-8901-e5177dcc3f04",
"weight":90
},
{
"model":"mistral-medium",
"endpointId":"d2b3c0e7-0a7f-4e63-8901-e5177dcc3f04",
"weight":10
}
],
"suspendDuration":"20"
}
```
- After:
```json
{
"production":[
{
"model":"mistral-medium",
"endpointId":"e910d0e5-d4d4-4a22-85dc-7e9e9228c721--PRODUCTION",
"endpointName":"Default Production Endpoint",
"weight":100
}
],
"sandbox":[
{
"model":"mistral-small-latest", …
```
> Improve AI API policy parameters to include endpointName

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Resolves: https://github.com/wso2/api-manager/issues/3681
Fixes the issue where the **Deploy** button remains enabled in **Deploy New Revision** when the previous deployment is still pending approval.
Added a condition to check whether the selected environment's deployment is in created state. This fixes the `Deploy` button remaining enabled even when the gateway radio button is not selected.
> Fix: Disable Deploy Button for Pending API Revision Deployment Approval

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/OpenAPI/Steps/ProvideOpenAPI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/Linting/Linting.tsx
- portals/publisher/src/main/webapp/source/src/app/data/api.js
Validate the associated governance rulesets in the API definition linter, in addition to the default Spectral ruleset and the ruleset from the tenant config.
- Updated the `getLinterResultsFromContent` function to handle multiple rulesets
- Note: This only supports the Spectral formats available in the currently used version of the `@stoplight/spectral-formats` dependency. Newer versions may support additional formats.
- No UI Changes
> Support validating gov rulesets in API definition linter UI

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/APISecurity/components/ApplicationLevel.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/ApiKeyHeader.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/AuthorizationHeader.jsx
This Pr will fix the issue : https://github.com/wso2/api-manager/issues/3652 related to the APIKey header and authorization Header.
Also, this will disable the Text inputs when the Security level is not checked.
> Fix UI issues in updating APIKey header and Authorization header

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/ImageGenerator.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/ThumbnailView.jsx
Fix https://github.com/wso2/api-manager/issues/3762
This fix resolves an issue where API thumbnails were not displayed in the Publisher UI after migrating from APIM-3.2.0. The issue occurred because the theme was not retrieved properly, causing errors when rendering the API grid view. Updating the way useTheme() is assigned ensures correct theme retrieval and proper thumbnail display.
> Fix API Thumbnail Retrieval Issue in Publisher UI After Migration

- portals/publisher/src/main/webapp/site/public/css/main.css
This PR fixes the issue where a shadow appears at the top of the progress bar.
> Fix UI issue where loading message shows a shadow on top

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Credentials/Wizard/CreateAppStep.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/Overview.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/ApplicationFormHandler.jsx
- portals/devportal/src/main/webapp/source/src/app/data/api.jsx
The Devportal currently displays only 25 application or subscription level policies, regardless of the total number available. Users cannot modify this default limit.
This fix allows users to configure this limit via settings.json. 
Added a new property for throttling-policy limit in settings.json under the app object.
Updated the frontend API call to send this limit (if configured) with the request.
```
app: {
throttlingPolicyLimit : 50,
}
```
Fix: https://github.com/wso2/api-manager/issues/3775
> Add configurable limit to display throttling policies in devportal

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
- portals/publisher/src/main/webapp/source/src/app/data/Constants.js
Fix https://github.com/wso2/api-manager/issues/3590
This pull request adds support for configuring connection timeouts and proxy settings at both global and endpoint levels. Additionally, connection timeouts and proxy configurations can be disabled at the endpoint level.
Related backend PR: https://github.com/wso2/carbon-apimgt/pull/13054
> Add support for global connection timeout and proxy configurations

- portals/admin/src/main/webapp/source/src/app/components/Organizations/AddEditOrganization.jsx
> Allow the organization reference ID to be editable.
> Fixes https://github.com/wso2/api-manager/issues/3831
> Remove the logic that makes the organization reference ID editable only when creating a new organization.
> [B2B Feature] Enable Editing of Organization Reference ID

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/Resources.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/OperationsSelector.jsx
> - An error occurs when common `parameters` exist for a set of paths in the API definition. When enabling or disabling security, the `parameters` array is incorrectly considered as an `operation` in the current logic. 
> - Fix https://github.com/wso2/api-manager/issues/3824
> - Add a check to exclude the `parameters` array from being processed as an `operation`.
> Fix treating the common parameters array as an operation

- portals/admin/src/main/webapp/source/src/app/components/APISettings/ApisTableContent.jsx
There are a set of issues when updating the api provider name in admin portal. https://github.com/wso2/api-manager/issues/3735. This PR fixes those. 
1. Only one row is made editable in the table in change api provider page to prevent invalid updates between entries when multiple rows are in the edit mode at the same time.
2. Added an alert to catch and display invalid tenant name errors.
> Fix change api provider bugs

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyList.tsx
In the publisher portal, when logged in as an observer user, 
- Deploy button is clickable on the deployments table
- Add Operation policies button is visible 
This PR fixes those by restricting the button based on `'apim:api_create'` and `'apim:api_publish'` scopes.
Fixes: https://github.com/wso2/api-manager/issues/3605
> Disable buttons in policy and deployment pages for Observer user.

- portals/admin/src/main/webapp/source/src/app/components/AdvancedSettings/TenantConfSave.jsx
- portals/admin/src/main/webapp/source/src/app/components/Throttling/Custom/AddEdit.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/APIDefinition.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/AsyncApiEditorDrawer.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/SwaggerEditorDrawer.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/APIDefinition/WSDL.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/components/DescriptionEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/MarkdownEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Prototype/MockScriptOperation.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/SOAPToREST/PolicyEditor.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Resources/components/operationComponents/SOAPToREST/SOAPToRESTListing.jsx
- portals/publisher/src/main/webapp/source/src/app/components/ServiceCatalog/Listing/Overview.jsx
- tests/cypress/integration/admin/10-advanced-configurations.spec.js
- tests/cypress/integration/publisher/011-lifecycle/03-add-custom-lifecycle-state.spec.js
Resolve issues with Monaco Editor-based UI components (e.g., API definition editor) not loading in offline environments in API-M versions 4.4.0 and 4.5.0.
This is caused by Monaco resources being fetched from a CDN by default, and therefore we need to $subject.
Note: UI test failures which resulted from the above fix has also been addressed by handling the uncaught exception.
Fixes: https://github.com/wso2/api-manager/issues/3857
Ensure Monaco Editor resources are bundled from node_modules instead of being fetched from the internet.
Enable WSO2 API Manager UIs to function correctly even in environments without internet access.
1. Identified the usages of the Monaco Editor in publisher, devportal and admin portals
2. Reproduced the issue in each case
3. Applied the Monaco Loader …
> Load Monaco from node modules instead of CDN for offline viewing

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/AsyncAPI/ApiCreateAsyncAPI.jsx
Fixes [wso2/api-manager#3657](https://github.com/wso2/api-manager/issues/3657)  
When creating an Async API by providing a URL or uploading a file, the **subscription plan** was set to `null`. This caused issues where no default subscription policy was applied in the deployment.  
- Set the **default subscription policy** to `['AsyncUnlimited']`, ensuring that every Async API has a default subscription policy unless explicitly changed by the user.  
- This implementation follows the same approach as the REST API, where a default subscription policy is assigned unless a different value is explicitly set.  
- Applied the default policy value at the **reducer level** to ensure that the policy is set during the API creation process.
> Set default Subscription Plan during Async API creation

- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/EndpointOverview.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EditableParameterRow.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
Fixing https://github.com/wso2/api-manager/issues/3842
Allowing users to add secret custom parameters to the endpoint security (OAuth) of an API
Added the checkbox option to mark the parameter as a secret
Implemented the secret parameter hiding logic
https://github.com/user-attachments/assets/9ac74a7d-098e-45a4-8e0f-6b71e8a5ad05
N/A
> Support secret custom params in endpoint security config

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/TokenManager.jsx
Enhance the Developer Portal UI by restricting access to the **"REMOVE KEYS"** button in the **Application Keys** section, allowing only the **application owner** to remove OAuth keys.
In WSO2 API Manager's Developer Portal, applications can be **shared among users via groups**. However, **only the application owner** has full permissions to:
- Edit application details
- Generate or regenerate keys
- Update OAuth configurations
This change ensures that **removing keys** is also restricted to the **application owner**, aligning with the existing ownership-based permission model.
- Prevent non-owner users (who access applications via group sharing) from seeing or using the **"REMOVE KEYS"** button.
- Ensure only the application owner has full control over key lifecycle operations.
- Updated …
> Restrict OAuth key deletion to application owner only

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Create.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Documents/Edit.jsx
This PR ensures that file upload errors in API Documents are always visible to the user, regardless of the environment. Currently it's set to not show in production environments. Hence, we need to $subject, which will improve visibility and user experience by informing users of document creation failures and file upload failures.
Removed the conditional check for process.env.NODE_ENV !== 'production'. 
This change is applied to both document creation and editing flows ensuring both flows are fixed and `alerts` appear in each case.
- https://github.com/wso2/api-manager/issues/3947
> Show document creation error alerts in all environments

- portals/admin/src/main/webapp/source/src/app/components/KeyManagers/AddEditKeyManager.jsx
> When user migrating from IS as a resident KM to third-party KM admin portal not using third-party KM template for UI. This fix will allow third-party KM to rename as "Resident Key Manager" and use third-party KM template at same time. 
Related issues - https://github.com/wso2/api-manager/issues/3909
> Change the logic to identify resident key manager using KM type.
> Allow third-party KM to rename as resident key manager

- tests/cypress/integration/publisher/003-run-time-configs/04-enable-mutual-ssl-and-upload-certificate.spec.js
Purpose of this PR is to fix the failing `04-enable-mutual-ssl-and-upload-certificate` test
Replaced a flaky selector with a more robust one.
N/A
`
> Fix failing mutual ssl UI test

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/GeneralConfiguration/EndpointSecurity.jsx
The purpose of this PR is to fix https://github.com/wso2/api-manager/issues/3984
Note: The bug mentioned in the above issue was already fixed with a different approach, but it leads to several other bugs. Therefore, fixed the issue with a new approach.
Preventing runtime errors and minor bugs in undefined sandbox endpoint scenario
Added initial/default values and null checks to the attributes
Improved state change logics
https://github.com/user-attachments/assets/f6ef5038-9fc9-4754-b6e6-2a219ef5625c
Prior to this change, if the above actions were done, it will create an unwanted proxyConfig element as below:
> Add null safety to proxy config and custom param updates

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/AttachedPolicyForm/General.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Policies/PolicyConfigurationEditDrawer.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/PoliciesUI/AttachedPolicyCard.tsx
- tests/cypress/integration/publisher/017-api-policies/01-api-specific-policy.spec.js
Purpose of this PR is to fix https://github.com/wso2/api-manager/issues/3999
Fix version mismatch issue in attached policy view/edit drawer
Used the `policyVersion` along with the `policyName` when searching the attached policy specification from the policies list
Updated the UI test to verify the functionality
> Fix version mismatch issue in attached policy view/edit drawer

- tests/cypress/integration/publisher/017-api-policies/01-api-specific-policy.spec.js
Fixing the failing API specific policy test
The test has been failing as the "Done" button was removed from the API policy view modal
Update API specific policy test to use close button for closing policy view modal
> Fix the failing API specific policy test

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditVhost.jsx
This PR fixes the VHost configuration by updating default port values for external GWs and correcting the DTO mapping.
- **Updated default ports in `AddEditVhost.jsx` and `AddEditGWEnvironment.jsx` for external GWs:**
- HTTP port: `8280` → `80` (standard HTTP port)
- HTTPS port: `8243` → `443` (standard HTTPS port)
- **Fixed VHost DTO mapping:**
- Added missing `httpContext` field mapping
- Updated `httpPort` and `httpsPort` to use dynamic values from vhost object instead of hardcoded values
- https://github.com/wso2/api-manager/issues/4109
> Fix VHost default port configuration and DTO mapping

- portals/devportal/src/main/webapp/site/public/locales/en.json
- portals/devportal/src/main/webapp/source/src/app/AppRouts.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/GoToTryOut.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/APIThumbPlain.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Applications/Details/Subscriptions.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Base/Errors/ResourceNotFound.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Base/Header/GlobalNavbar.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Shared/PortalModeRouteGuard.jsx
- portals/devportal/src/main/webapp/source/src/app/utils/PortalModeUtils.js
- portals/publisher/src/main/webapp/site/public/locales/en.json
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Apis.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/components/APIDetailsTopMenu.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Errors/ResourceNotFound.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Errors/ResourceNotFoundError.tsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/navbar/GlobalNavLinks.jsx
- portals/publisher/src/main/webapp/source/src/app/components/PublisherLanding/index.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Shared/MCPRouteGuard.jsx
This PR handles the MCP Server support enabled and disabled flows.
- When MCP Support is **disabled**
- When MCP Support is **enabled**
There are 3 portal modes that need to be taken into consideration. Namely, `API_ONLY`, `MCP_ONLY` and `HYBRID`.
- HYBRID mode
- API_ONLY mode
- MCP_ONLY mode
> Handle MCP Server support disabled mode in Publisher portal and Developer portal

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/ListGatewayInstances.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/index.jsx
This PR adds default sorting functionality to the Gateway Instances table and fixes a route props issue for MCP environments to prevent unnecessary component remounting.
- Added default sorting by **Last Active** column in descending order
- Most recently active gateways now appear at the top by default
- Users can still manually sort by any column as needed
- Fixed route props passing for MCP environments page to avoid unmount and remount cycles
- Changed from `component` to `render` prop to prevent component recreation during API deployment polling
**Related Issues:**
- [wso2-apim-internal#9923](https://github.com/wso2-enterprise/wso2-apim-internal/issues/9923)
> Add gateway table sorting and fix MCP route remounting issue

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/NewOverview/CustomizedStepper.jsx
- Resolves: https://github.com/wso2/api-manager/issues/4154
This pull request refactors the `CustomizedStepper` component to improve handling of MCP servers created using an existing API, particularly with respect to endpoint detection and deployment logic. The changes enhance the logic for checking endpoint availability, and clarify deployment checks.
* Refactored the logic for MCP server endpoints in `useEffect`: now distinguishes between EXISTING_API subtype (fetches underlying API and checks its endpoint config) and DIRECT_BACKEND/SERVER_PROXY subtypes (uses `getMCPServerEndpoints`). This ensures endpoint checks are accurate based on the MCP API subtype. [[1]](diffhunk://#diff-a2ea58fe0845e79d8f97cbff0b5b4386a94888288da2e1c90d6d0c39405518ebL199-R220) …
> Fix overview links not working issue for MCP servers created using an existing API

- portals/devportal/src/main/webapp/source/src/app/components/Shared/AppsAndKeys/ViewKeys.jsx
> Fixes the following https://github.com/wso2/api-manager/issues/4058
> The property 'enableTokenGenForMappedApps' : true , should be added to the settings.js of devportal for the feature to be enabled.
> Enable token generation for provisioned applications

- portals/admin/src/main/webapp/site/public/conf/settings.json
- portals/devportal/src/main/webapp/site/public/theme/settings.json
- portals/publisher/src/main/webapp/site/public/conf/settings.json
Related to: https://github.com/wso2/api-manager/issues/4105
OIDC Federated Logout Endpoint Not Invoked When Skip Logout Consent Is Enabled
Before APIM 4.4.0, logoutSessionStateAppender was set to an empty value. Change this to "OIDC" as it is required for the B2B feature. Afterward, revert logoutSessionStateAppender back to an empty value ("").
> Set logoutSessionStateAppender to empty

- portals/devportal/src/main/webapp/WEB-INF/web.xml
- portals/devportal/src/main/webapp/source/src/app/AppRouts.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Apis.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/CommonListing.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Base/Header/Search/HeaderSearch.jsx
- portals/devportal/src/main/webapp/source/src/app/components/Base/index.jsx
- portals/devportal/src/main/webapp/source/src/app/components/MCPServers/MCPServers.jsx
- portals/publisher/src/main/webapp/WEB-INF/web.xml
- portals/publisher/src/main/webapp/source/src/app/ProtectedApp.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Apis.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Base/Header/headersearch/HeaderSearch.jsx
- Related issue: https://github.com/wso2/api-manager/issues/3978
This pull request introduces a unified `/search` route for both the DevPortal and Publisher portals, replacing previous `/apis/search` and `/mcp-servers/search` endpoints. The changes ensure that search results are now accessed via `/search`, streamline routing logic, and update UI components to reflect the new search view.
**Unified Search Routing and UI Updates**
* Added `/search` servlet mapping in both `devportal` and `publisher` `web.xml` files to support the new unified search endpoint. [[1]](diffhunk://#diff-a884529b8dc829e3a8de30c51f69a0481d57699c5d4943f66c803b9dee9e4ff2R114) [[2]](diffhunk://#diff-11070c476af89b747a66f5eddf5dcae113c673bc638545535cf837a165a770e4R137)
* Updated React routing in `AppRouts.jsx`, …
> Fix search result rendering issues in publisher and developer portals

- portals/devportal/src/main/webapp/source/src/app/components/Apis/Listing/APICards/ApiThumbClassic.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
Fixing the issue where it shows the type as REST in MCP servers
Fixed the logic to handle MCP type separately
> Fix MCP chip rendering logic

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Configuration/RuntimeConfiguration.jsx
This pull request makes a minor update to the `RuntimeConfiguration` component. The main change is the removal of the `apiType` property from the `apiConfig` object before calling the `updateAPI` function, which helps ensure only the intended configuration data is sent during updates.
* Removed the `apiType` property from the `apiConfig` object before updating the API in the `RuntimeConfiguration` component (`RuntimeConfiguration.jsx`). [[1]](diffhunk://#diff-ef823f021e800ad34a772a4b2d7359930a703f3a36ba035fbf18b4a23a22c6b4R583) [[2]](diffhunk://#diff-ef823f021e800ad34a772a4b2d7359930a703f3a36ba035fbf18b4a23a22c6b4R614)
> Fix issue with API save within the runtime configurations page

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Listing/components/ImageGenerator/APICards/ApiThumbClassic.jsx
- tests/cypress/integration/publisher/011-lifecycle/04-depricate-old-versions.spec.js
- tests/cypress/integration/publisher/018-third-party-api/00-publish-third-party-api.spec.js
Previously, in publisher portal unified search results, the lifecyclestate of the APIs were not loading unless the card is hovered. Purpose of this PR is to fix that issue.
Fixes https://github.com/wso2/api-manager/issues/4052
Corrected the ordering of the lifecycle state handling logic.
Updated the tests accordingly
N/A
> Fix lifecycle state chip rendering issue in search results

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
Fixes https://github.com/wso2/api-manager/issues/4337
Fixes https://github.com/wso2/api-manager/issues/4338
Added optional chaining, so the page won't crash due to undefined values
Hide the revisions title in read only mode and revision mode
https://github.com/user-attachments/assets/94860891-a19a-41e2-bc0b-b53dd0cd2787
> Add optional chaining to prevent errors when accessing gateway revisions

- portals/admin/src/main/webapp/source/src/app/components/GatewayEnvironments/AddEditGWEnvironment.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/APICreateRoutes.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Components/DefaultAPIForm.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/CreateAPIWithAI/APICreateWithAI.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Create/Default/APICreateDefault.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/DeploymentOnbording.jsx
- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Environments/Environments.jsx
This PR adds read_only gateway mode filtering for create API UIs.
Related PR - https://github.com/wso2/carbon-apimgt/pull/13422
When there are no environments with 'WRITE_ONLY' or 'READ_WRITE' modes other than Universal gateway, the UI looks like below. The API will be deployed to Universal Gateway by default.
**Admin Portal View**
**Publisher portal Create API View**
When there are environments with at least one of 'WRITE_ONLY' or 'READ_WRITE' modes, the UI looks like below.
**Admin Portal View**
**Publisher portal Create API View**
> Add read_only gateway mode filtering for create API UIs

- portals/publisher/src/main/webapp/source/src/app/data/defaultTheme.js
This pull request makes a minor update to the analytics link in the default theme configuration. The link for the left menu analytics now points to a new onboarding URL.
- Changed the `leftMenuAnalytics.link` in `defaultTheme.js` to use `https://www.moesif.com/wrap/basic?onboard=true` instead of the previous URL.
> Update moesif analytics link

- portals/publisher/src/main/webapp/source/src/app/components/MCPServers/Details/Endpoints/AddEditEndpoint.jsx
- Resolves: https://github.com/wso2/api-manager/issues/4376
This pull request refines the handling of endpoint security configuration in the `AddEditEndpoint` component. The main improvement is ensuring that sensitive fields like `clientSecret` and `password` are not unintentionally overwritten with placeholder values, and that the security object is properly reset or enabled based on the selected security type.
**Endpoint security configuration improvements:**
* Updated `saveEndpointSecurityConfig` to clear placeholder values (`'******'`) for `clientSecret` and `password`, preventing accidental storage of placeholders.
* Ensured that when the security type is `'NONE'`, the configuration resets to default values, and for other types, the `enabled` flag is set to `true`.
* Updated Redux …
> Fix MCP backend security configuration issues

- portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Endpoints/Endpoints.jsx
Fixes a NullPointerException that occurs when trying to access the Endpoints page of Server-Sent Events (SSE) APIs in the API Publisher.
The code was incorrectly attempting to fetch Swagger definitions for SSE APIs using the REST API Swagger retrieval method (`api.getSwagger()`). This caused a NPE in `OASParserUtil.getSwaggerVersion()` when the parser tried to process a null/invalid specification returned for the SSE API.
Extended the existing condition that excludes WebSocket APIs from Swagger fetching to also exclude SSE APIs:
- **Before:** `api.type !== 'WS'` 
- **After:** `!['WS', 'SSE'].includes(api.type)`
- SSE API Endpoints pages now load without errors
- Maintains existing functionality for all other API types
- https://github.com/wso2/api-manager/issues/4139
> Fix SSE API endpoints page NPE by excluding SSE from Swagger fetch
